### ISSUE TITLE
Appengine Tests

### ISSUE THREAD

**Issue by ulrichSchreiner** [smartystreets/goconvey#101]
Hi,

is it possible to run appengine-tests? At commandline you start them by "goapp test" and inside the tests you have the appengine packages available. When starting "goconvey" i get build failures that the appengine modules are not found (that is correct with the "go" tool, but not with the "goapp" tool which is the equivalent in the appengine-sdk).

thanks
</usc>

**Comment by mblasi** [comment]
Hi, sorry for asking on this closed issue, but I'm facing the same.

I have just a simple test, using aetest package, and datastore stuf, and that works for me by running "goapp test" in command line.

Now, I want to get convey UI running, and I just get the same error as I run "go test":

`/home/devuser/sandbox/testproject1/src/github.com/astaxie/beegae/session/sess_cookie.go:186: cannot use cookiepder (type *CookieProvider) as type Provider in argument to Register:
	*CookieProvider does not implement Provider (wrong type for SessionDestroy method)
		have SessionDestroy(string) error
		want SessionDestroy(context.Context, string) error
`

Though, I tried to use the -gobin parameter, specifying the goapp binary, without success (in several ways: full path, just the binary, and also created an alias go=goapp)
There is no way to get my test run with goapp test in convey.

Could you tell me if I am doing any mistake?

Regards,
Matías.

**Comment by mdwhatcott** [comment]
Hmm, it sounds like you are going about it in the correct way. I'm not sure what's up.

**Comment by mblasi** [comment]
Ok, here is the reason:
I am using beegae, and I got that using go instead of goapp: https://github.com/astaxie/beegae/issues/6

I removed the sources, I run goapp get github.com/astaxie/beegae, and it worked!

Thanks,
Matías.
