### ISSUE TITLE
ShouldPanic doesn't catch panics, and it should, shouldn't it?

### ISSUE THREAD

**Issue by glycerine** [smartystreets/goconvey#108]
The title says it all. How else are you supposed to test code for correct panics?

sample code:

``` go
package main

import (
    "testing"
    cv "github.com/smartystreets/goconvey/convey"
)

func Ipanic() int {
    panic("I panic")
    return 0
}

func TestSpec(t *testing.T) {

    cv.Convey("ShouldPanic should halt the panic, should it not?", t, func() {
        cv.So(Ipanic(), cv.ShouldPanic)
    })
}
```

sample run:

```
jaten@i7:~/tmp/tmp$ go test


Errors:

  * /home/jaten/tmp/tmp/t_test.go
  Line 9: - I panic
  goroutine 3 [running]:
  runtime.panic(0x504140, 0xc21000a710)
    /usr/cn/go1.2rc3/go/src/pkg/runtime/panic.c:248 +0x106
  _/home/jaten/tmp/tmp.Ipanic(0xc21004f600)
    /home/jaten/tmp/tmp/t_test.go:9 +0x55
  _/home/jaten/tmp/tmp.func·001()
    /home/jaten/tmp/tmp/t_test.go:16 +0x1e
  _/home/jaten/tmp/tmp.TestSpec(0xc210053000)
    /home/jaten/tmp/tmp/t_test.go:17 +0xfa
  testing.tRunner(0xc210053000, 0x6f01c0)
    /usr/cn/go1.2rc3/go/src/pkg/testing/testing.go:389 +0x8b
  created by testing.RunTests
    /usr/cn/go1.2rc3/go/src/pkg/testing/testing.go:469 +0x8b2

  goroutine 1 [chan receive]:
  testing.RunTests(0x5a9958, 0x6f01c0, 0x1, 0x1, 0x1)
    /usr/cn/go1.2rc3/go/src/pkg/testing/testing.go:470 +0x8d5
  testing.Main(0x5a9958, 0x6f01c0, 0x1, 0x1, 0x6f83c0, ...)
    /usr/cn/go1.2rc3/go/src/pkg/testing/testing.go:401 +0x84
  main.main()
    _/home/jaten/tmp/tmp/_test/_testmain.go:47 +0x9c



1 assertion thus far

--- FAIL: TestSpec (0.00 seconds)
FAIL
exit status 1
FAIL    _/home/jaten/tmp/tmp    0.003s
```

**Comment by KielChan** [comment]
> Excellent point! `ShouldPanic` (and its variants) should indeed recover panics. And they do, provided that you satisfy a few conditions.
> 
> In order for GoConvey to recover the panic you must pass the function, not the result derived by calling the function. So, the line where you call `so`:
> 
> ```
> cv.So(Ipanic(), cv.ShouldPanic)
> ```
> ...should actually look like this:
> 
> ```
> cv.So(Ipanic, cv.ShouldPanic)
> ```
> Notice that the function is not being called. That is the job of GoConvey--only then can the panic be recovered gracefully. Once you try that you will notice another problem: the assertion will still fail but with this message:
> 
> ```
> You must provide a void, niladic function as the first argument!
> ```
> The function you have defined, `Ipanic` is niladic (has no input parameters) but it returns an `int` and is therefore, not void. So, lets say you have a method that has a few input parameters and/or returns a value. How can you use it with `ShouldPanic`? Here's the answer:
> 
> ```
> cv.So(func() { Ipanic() }, cv.ShouldPanic)
> ```
> Notice that I've wrapped `Ipanic` in a void, niladic function, in which I call `Ipanic`. I'm not calling the wrapper, GoConvey will do that and recover the panic as expected. This behavior is [documented](http://godoc.org/github.com/smartystreets/goconvey/assertions#ShouldPanic) and [tested](https://github.com/smartystreets/goconvey/blob/master/assertions/panic_test.go#L12), but isn't the most intuitive thing to learn if you haven't done an exhaustive reading. Feel free to close the issue if that solves it for you or comment further if you have any other concerns.

shouldPanicWith not work as expected:
```golang
So(func() { MustInit(fakeCfgPath) }, ShouldPanicWith, errors.New("fake load err"))
```
```
 Expected func() to panic with 'fake load err' (but it panicked with 'fake load err')!
```
@mdwhatcott
