### ISSUE TITLE
Scoping needs better documentation

### ISSUE THREAD

**Issue by newhouseb** [smartystreets/goconvey#111]
Scoping with goconvey can be very counter-intuitive:

``` go
func TestFoo(t *testing.T) {
    Convey("Get foo", t, func() {
        foo := getFoo()
        Convey("Print one version", func() {
            t.Log(foo)
        })
        Convey("Print another version", func() {
            t.Log(foo)
        })
    })
}
```

In this case, `getFoo()` will be run twice, but both conveys will reference the same foo. So if `getFoo()` returns `1` and then `2`, the test log will print `1` twice.

I'm pretty sure that this is because the closures close around the required variables the first time the parent closure is executed, not when they are actually to be run. This ends up looking as if `foo` is being captured by value instead of by reference, but go closures are always capture by reference (I realize that this in fact _not_ capture by value, it's an illusion). To get the result I'd expect, I need to write my code as follows:

``` go
func TestFoo(t *testing.T) {
    var foo string
    Convey("Get foo", t, func() {
        foo = getFoo()
        Convey("Print one version", func() {
            t.Log(foo)
        })
        Convey("Print another version", func() {
            t.Log(foo)
        })
    })
}
```

This way, there is only one reference to `foo` anywhere and therefore the return value from `getFoo()` won't bind to some orphaned `foo` reference. I haven't yet read goconvey's internals so I don't have a good sense for what concurrent execution already exists (if any), but the fact that I get my desired behavior by expanding resource sharing makes me a little concerned.

The examples all implicitly recognize this, but there's nothing in the documentation that explains why this behavior must be so. Is this the only way the goconvey can work? Could goconvey be modified to re-evaluate all the closures so that the original version works as I originally thought it would? Would this be idiomatically the right™ way for things to work? I'm relatively new to golang and to BDD (but not TDD), and I'd be happy to add something to the FAQ about this but I wanted to make sure I have my thought process correct.

Goconvey is great. I'd love to help any way I can.

**Comment by pkufranky** [comment]
> ed, rather than the default, 'isolated' behavior. Would that be helpful or just add confusion



> On a side note, I've also thought about adding a new top-level `SequentialConvey` function that simply executes all nested `Convey`

Here is a case that SequentialConvey is needed, but not on the top level. @mdwhatcott 

```
Given an old page (a)
    When cloned (b)
        side effect 1 should happend (c1)
        and side effect 2 should happend (c2)
        and side effect 2 should happend (c3) 
```

The execution order is abc1abc2abc3, however, i want the order abc1c2c3. The reason is
- b is a heavy task, for efficiency
- b may output many logs, no need to show the log multiple times
- it is intuitive to clone once, and check 3 side effects separately

To avoid executing b multitimes, there are two ways, but they are both tricky

- deeply nested. too many levels
```
Given an old page (a)
    When cloned it (b)
        side effect 1 should happend (c1)
            and side effect 2 should happend (c2)
                and side effect 2 should happend (c3)   
```
- use convey.Print instead of Convey
```
Given an old page (a)
    When cloned it (b)
        side effect 1/2/3 should happend (c)
            # c1, c2, c3 use convey.Print instead of convey.Convey
            and side effect 1 should happend (c1)
            and side effect 2 should happend (c2)
            and side effect 2 should happend (c3)   
```

**Comment by mdwhatcott** [comment]
@pkufranky - FYI, I'm no longer a maintainer of this repo.
