### ISSUE TITLE
Ignore folders when searching for tests

### ISSUE THREAD

**Issue by emicklei** [smartystreets/goconvey#176]
I noticed that running goconvey also navigates my /examples folder for tests and tries to build go files found inside them.  In my project, this causes a build failure as some of these examples require a specific setup (e.g. appengine).

My suggestion is the have a .goconvey file containing folder names to skip (similar to .gitignore).

**Comment by braindev** [comment]
I added a PR for this.  https://github.com/smartystreets/goconvey/pull/368

**Comment by thomasmodeneis** [comment]
Hi,

Sorry but is still unclear for me by reading the docs for this change how can I ignore a node_modules folder.
I've tried by adding the `example.goconvey` with the following contents:
```
// Uncomment the next line to disable the package when running the GoConvey UI:
IGNORE
```
But is unclear how can I define a set of folders that must be ignored.

Any hints ?
Cheers.

**Comment by braindev** [comment]
@thomasmodeneis did you try:

`goconvey -excludedDirs node_modules`
