### ISSUE TITLE
Consider using the race detector

### ISSUE THREAD

**Issue by mholt** [smartystreets/goconvey#191]
Let's look into supporting the race detector tool. It would be especially nice if the GUI would raise a flag if there's a race condition. It could be optional (we have an options drop-down panel to facilitate that).

**Comment by sybrandy** [comment]
I hate to resurrect an old issue, but does this mean that the race detector will not be supported in the UI or is that still planned?

**Comment by tyranron** [comment]
+1 for supporting race detector in Web UI or in cmd interface (like `-cover` option).
