### ISSUE TITLE
time.Time and ShouldEqual not kissing in a tree

### ISSUE THREAD

**Issue by troyk** [smartystreets/goconvey#194]
Apologies if this is off the mark, super new to go and this threw me; can not get time.Time to pass a ShouldEqual test (this is not my actual test, just enough to reproduce).   goconvey is at least 25% of the reason I'm giving go a go, so big shout out, big time luv'n.

``` go
func TestCoalesce(t *testing.T) {
    Convey("TestTime", t, func() {
        now := time.Now()
        fmt.Println(now == now) // true
        So(now, ShouldEqual, now)
    })
}
```

**Comment by rana** [comment]
ShouldYouNeed:ShouldEqualTime
```
func ShouldEqualTime(actual interface{}, expected ...interface{}) string {
	if len(expected) != 1 {
		return fmt.Sprintf("Expected parameter count invalid (expected:1 actual:%v)", len(expected))
	}
	a, ok := actual.(time.Time)
	if !ok {
		if actual == nil {
			return fmt.Sprintf("Actual is nil")
		}
		return fmt.Sprintf("Actual value is not a time.Time type (type:%v)", reflect.TypeOf(actual).Name())
	}
	e, ok := expected[0].(time.Time)
	if !ok {
		if expected[0] == nil {
			return fmt.Sprintf("Expected is nil")
		}
		return fmt.Sprintf("Expected value is not a time.Time type (type:%v)", reflect.TypeOf(expected[0]).Name())
	}
	if reflect.TypeOf(expected[0]) != reflect.TypeOf(actual) {
		return fmt.Sprintf("Token types aren't equal (expected:%v actual:%v)", reflect.TypeOf(expected[0]).Name(), reflect.TypeOf(actual).Name())
	}
	if !e.Equal(a) {
		return fmt.Sprintf("Tme values aren't equal (type:%v expected:%v actual:%v)", reflect.TypeOf(actual).Name(), e.String(), a.String())
	}
	return ""
}
```

**Comment by mdwhatcott** [comment]
Another option:

`So(actualTime, ShouldHappenWithin, time.Duration(0), expectedTime)`

I just had a few thoughts about this issue (which is really an issue with the [assertions](https://github.com/smartystreets/assertions) package). I've opened [another issue in that repo](https://github.com/smartystreets/assertions/issues/20) to continue the discussion.

**Comment by mdwhatcott** [comment]
Yet another option:

`So(actualTime.Equal(expectedTime), ShouldBeTrue)`

(But the failure message will leave much to be desired...)

**Comment by mdwhatcott** [comment]
@rana - I would probably name that method: `ShouldHappenOn` so it would fit with the other time-related assertions. Thanks for sharing that example!

**Comment by rana** [comment]
@mdwhatcott - You're welcome, rename and use as you need. 
Cheers

**Comment by mdwhatcott** [comment]
I'm reopening this issue because of [recent work on the Assertions package](https://github.com/smartystreets/assertions/issues/20). The proposed changes could possibly cause differing test results. Your comments are welcome.

**Comment by mdwhatcott** [comment]
As a result of https://github.com/smartystreets/assertions/pull/21 this issue is now resolved. My recommendation moving forward is to use `ShouldEqual` when comparing `time.Time` values.
