### ISSUE TITLE
Code coverage results in a 404 on Windows

### ISSUE THREAD

**Issue by MindTwister** [smartystreets/goconvey#219]
When attempting to retrieve the coverage report from the interface the link results in a 

```
404 page not found
```

The coverage is reported correctly
# Steps to reproduce

Current setup
- Go version 1.2.2 (windows/amd64)
- Goconvey - commit 53671f9
- Windows 7
1. Run `goconvey` from the command line
2. Click a file in the coverage list
## Expected

A coverage report
## Actual

A 404

**Comment by MrGuoRanDuo** [comment]
https://github.com/smartystreets/goconvey/issues/619#issuecomment-1980343642

**Comment by MrGuoRanDuo** [comment]
#619
