### ISSUE TITLE
Support build tags

### ISSUE THREAD

**Issue by attilaolah** [smartystreets/goconvey#249]
Add a `tags` flag and pass it along to `go test`, so that I can run `goconvey -tags=integration` and it would include my `*_test.go` files that are tagged with `// +build integration`.

**Comment by thomasmodeneis** [comment]
Hi @attilaolah 
I could not figure out how #176 solved the flags for integration test.
I've just tried to run convey to trigger the execution of some test flagged with the // +build integration, however I'm getting this error:
```
goconvey  -tags=integration 
flag provided but not defined: -tags
Usage of goconvey:
  -cover (...)
```

Any ideas on how this could be executed correctly ?
Thanks you.

**Comment by igormoochnick** [comment]
+1

**Comment by GJRTimmer** [comment]
+1
\
