### ISSUE TITLE
Cmd+C or Ctrl+C shouldn't open composer

### ISSUE THREAD

**Issue by mholt** [smartystreets/goconvey#252]
I can't figure out why this is happening, but when you use a keyboard shortcut like Cmd+C or Ctrl+C to copy (or any other key combination with C), the code composer opens. Right now the UI has this code in goconvey.js:

```javascript
// Keyboard shortcuts!
$(document).keyup(function(e)
{
	if (e.ctrlKey || e.metaKey || e.shiftKey)
		return;

	switch (e.keyCode)
	{
		case 67:		// c
			$('#show-gen').click();
			break;
		case 82:		// r
			$('#run-tests').click();
			break;
		case 78:		// n
			$('#toggle-notif').click();
			break;
		case 87:		// w
			$('#path').focus();
			break;
		case 80:		// p
			$('#play-pause').click();
			break;
	}

	return suppress(e);
});
```

But notice that we're checking to see if the meta or control keys are also pressed for that event, and if so, we do nothing. Anyone is welcome to tackle this, or I'll try to look at it when I get a chance...

**Comment by mdwhatcott** [comment]
Fixed by https://github.com/smartystreets/goconvey/pull/296
