### ISSUE TITLE
Unable to View Test Coverage

### ISSUE THREAD

**Issue by ghost** [smartystreets/goconvey#253]
In the Web UI, the test coverage link is broken and points to:
http://localhost:8080/reports/_-Users-ever-Dev-go-src-forecast.html

`/Users/ever/Dev/go` is my $GOPATH and /src/forecast is where the project files are being stored, so somehow the link is grabbing my $GOPATH.  If I edit the link to read: http://localhost:8080/forecast.html a good looking coverage report comes up, however it's outdated and looks like it was created on my very first project save, but not since then.

If I go to `$GOPATH/src/github.com/smartysteets/goconvey/web/client/reports` I can see two files related to my project:
1. forecast.html (the outdated coverage report)
2. forecast.txt which contains:

```
mode: set
_/Users/ever/Dev/go/src/forecast/app.go:16.45,18.2 1 1
_/Users/ever/Dev/go/src/forecast/app.go:20.13,39.2 5 0
```

This .txt file updates on every project file save and appears to be working correctly.  In the WEB UI, when I hover over coverage, it says 16.7% test coverage which appears correct and in line with what the .txt file is reporting.

So, it looks like the UI link and .html report are broken, but the UI coverage % and .txt file are working.

A couple questions:
1. How do I fix the link on the Web UI to pull up the HTML report?
2. How do I get the HTML report to update when I save a project file?

Version / Settings:

```
go version go1.3.3 darwin/amd64
2014/10/24 10:18:05 goconvey.go:52: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
```

Mac / OS X Yosemite

Great tool by the way!  Everything else has been super easy to use.

**Comment by sandy-adi** [comment]
![image](https://user-images.githubusercontent.com/636056/89234132-487c6780-d5b9-11ea-90d4-42c3e80b2137.png)
It appears like my agent is running without coverage, how can I enable this?
