### ISSUE TITLE
Web server seems to hog CPU even when idle!

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/goconvey#278]
I've noticed lately that goconvey is a big drain on resources, even when no file changes are being made. Focusing on a single small directory relieves the pressure, but the projects I've been working on aren't overly large.

I suspect it has something to do with the recent rewrite of the polling watch mechanism. Again, fsnotify would be great to use, except for the `too many open files` problem.

**Comment by akupila** [comment]
Possibly fixed with https://github.com/smartystreets/goconvey/pull/448
