### ISSUE TITLE
Support for Asynchronous Testing

### ISSUE THREAD

**Issue by xogeny** [smartystreets/goconvey#285]
I really like `goconvey`, but there are a few things that make it sub-optimal for general use.  One is the fact that a test case like this will generate a panic:

```
import "testing"

import . "github.com/smartystreets/goconvey/convey"

func TestAsync(t *testing.T) {
    Convey("Doing some asyn testing", t, func() {
        done := make(chan bool)

        go func() {
            So(2, ShouldEqual, 2)
        }()

        _ = <-done
    })
}
```

As I understand it, the issue is with the way contexts are managed and probably exacerbated by the use of `gls`.  I poked through the source code, but as far as I could tell, all the context management is unexported so I don't see a way to be able to express to `goconvey` the fact that the `So` here is associated with the `Convey`.

As it is, I end up having to "save up" data that I'd like to compare in a thread and some how get it back to the "real" thread so I can do the `So` call there (which is, obviously, pretty awkward).

Am I missing something?

**Comment by johntdyer** [comment]
This worked great in 1.4 but all of a sudden it is failing for me in 1.5.1

```
$ godep go test -v                                    on git:master|✚1
# _/Users/jdyer/Projects/go/src/bitbucket.org/voxeolabs/tropocli
./tropoCLI_test.go:217: undefined: C
./tropoCLI_test.go:330: undefined: C
FAIL	_/Users/jdyer/Projects/go/src/bitbucket.org/voxeolabs/tropocli [build failed]
godep: go exit status 2
```

#Test:
```go
func TestListAddress(t *testing.T) {
	s := &Session{}
	s.Username = "foo"
	s.Password = "bar"
	ts := serveHTTP(t)
	defer ts.Close()
	s.Baseurl = ts.URL
	s.initialize()

	Convey("TestListAddress", t, func(c C) {
		s.Comms.MainWaitGroup.Add(1)
		address := &Address{}
		err := json.Unmarshal(addressJSON(), address)
		So(err, ShouldBeNil)

		var wg sync.WaitGroup
		wg.Add(1)
		go func() {
			defer wg.Done()
			line := <-s.Comms.Msg
			c.So(line, ShouldEqual, "14155551212,45679,0\n")
		}()

		s.listAddress(address)
		wg.Wait()
	})
}

```

**Comment by mdwhatcott** [comment]
@johntdyer - What commit is the goconvey package at? 

`C` is still very much a part of that package:

https://github.com/smartystreets/goconvey/blob/master/convey/doc.go#L21

**Comment by johntdyer** [comment]
@mdwhatcott  - This was an old version, updating it  ( `go get -u ...` ) resolved it for me.  

-John
