### ISSUE TITLE
Break out webui into its own project.

### ISSUE THREAD

**Issue by james-lawrence** [smartystreets/goconvey#292]
First let me start by saying a I love the web ui.
One of the parts that bothers me though is the fact the UI relies on parsing the output of the tests.

Any chance we can break the web ui into its own project with a API for sending information to the server it will help integrating the ui with other testing frameworks that have reporting interfaces.

**Comment by james-lawrence** [comment]
one way would be actually have an api a test reporter can send results to.
Then you can have a test reporter that parses the standard test output or for other frameworks (like ginkgo) a simple reporter can be used that hits goconvey api with the test results.

**Comment by mdwhatcott** [comment]
That sounds an awful lot like what we currently have... So, how many separate CPU processes are you talking about here? Maybe you could diagram what you are thinking? A picture might just clear up the misunderstanding? 

The current parser could certainly be extended to parse other test frameworks like Ginkgo, etc...

**Comment by james-lawrence** [comment]
CPUs have nothing to do with this. =)

I'm trying to hook in ginkgo test framework with convey ui basically. Right now it fails because convey has no clue how to parse the output. However parsing the output isn't really necessary if the server provides an api layer I can just send test results to by registering a reporter that writes to that api. I'll do a diagram this weekend for you.

**Comment by james-lawrence** [comment]
[diagram](https://docs.google.com/drawings/d/1jOQxs3hE2P6LcGlWkxxnSH99apDkW1TzSAhk3i-7P1M/edit?usp=sharing).

**Comment by mdwhatcott** [comment]
Ok, thanks for the clarification. I don't have a good sense for how wide-spread the adoption of this would be. It's probably not something we at SmartyStreets would want to spearhead but if the community is interested in making it happen it's certainly possible.

**Comment by james-lawrence** [comment]
I'd be more than happy to do the work, just didn't want to run off and do it without a discussion around it to see if there would be interest in it.
