### ISSUE TITLE
Setting timeout

### ISSUE THREAD

**Issue by xogeny** [smartystreets/goconvey#295]
I've got some tests that take more than 5 seconds to run.  The first problem was figuring out that the timeout was the issue.  The timeout causes a panic which dumps a huge amount of output.  Finding the explanation for the panic is a bit tedious, but doable.  It would be nice if it were more obvious what the issue is.

But that is really secondary.  The real issue I'm facing now is specifying the `timeout` value.  If I run `goconvey -timeout=10s`, everything works.  But I created a file called `settings.goconvey` in the current directory that contains:

```
-timeout=10s
```

But when I run `goconvey`, it doesn't seem to pick up on this value.  It is a little hard to debug because `goconvey` doesn't actually output any information on what timeout value it is using.  But since the panic mentions a timeout value of `5s`, I'm assuming it isn't reading my `settings.goconvey` file.  What am I missing.  The documentation seems pretty clear in specifying the pattern to use for the file name.  But `goconvey` doesn't seem to be picking it up.

Any ideas?

**Comment by xogeny** [comment]
Doh!  I figured it out.  The issue is that child directories don't inherit from their parents.  The test in question was in a package stored in a sub-directory.  I incorrectly assumed that if I set `timeout` in the current directory, it would apply to `goconvey` in general.  But it turns out the settings are specifically limited to the package contained in the same directory as the `settings.goconvey` file.

I'll close this.  But I do think it would be a good idea to include some information about the settings used for each test to help make debugging these things easier.

**Comment by mdwhatcott** [comment]
Sorry for the run-around! Here's the current documentation for the Profile feature:

https://github.com/smartystreets/goconvey/wiki/Profiles

It looks like I should make explicit mention that a profile is for that package only and not nested packages.

**Comment by mdwhatcott** [comment]
Ok, I've added a note at the bottom...

https://github.com/smartystreets/goconvey/wiki/Profiles

Did you have anything else in mind for documenting the profile behavior?

**Comment by xogeny** [comment]
I think your note is sufficient for now.
