### ISSUE TITLE
Missing documentation for -timeout in *.goconvey

### ISSUE THREAD

**Issue by bithavoc** [smartystreets/goconvey#298]
There is no documentation on how to use `-timeout` in __*.goconvey__ files.

What are *.goconvey files? how do you create one?

I created one with the following names and it doesn't work:

* .goconvey
* test.goconvey
* project.goconvey

`-timeout` works fine as parameter for the `goconvey` program, but it's unclear how to create a file with the given param.

**Comment by mdwhatcott** [comment]
Sorry for the confusion!

Those files are called "profiles" in goconvey. Here's the existing documentation:

https://github.com/smartystreets/goconvey/wiki/Profiles

The wiki is editable by anyone, feel free to add any clarification you'd like.

**Comment by bithavoc** [comment]
Thanks!
