### ISSUE TITLE
Tips for making GPM/etc work with GoConvey? (Code outside GOPATH issues)

### ISSUE THREAD

**Issue by leeola** [smartystreets/goconvey#299]
Looks like Symlinks are quite a hairy subject with GoConvey. Recently i pulled GoConvey and immediately my tests all failed. After a bit of research, it seems that my project is failing in GoConvey because it exists outside of the active `$GOPATH`.

Currently i'm pinning to cbae630b709dcb8761726f27948aab4c125577ff _(right before 25a535f9fbd7c6cb0773b40eef6788fd4f917fc1, which adds checks for symlinks)_ and all seems to be well.

With that said though, is GoConvey going to be able to support projects outside of the GOPATH? Many of the Go "package managers" create this workflow, and it's quite desired for many people *(myself included)*, so i'm curious how GoConvey plans to interact with this.

**Comment by mdwhatcott** [comment]
Sorry about the trouble @leeola !

We don't have any plans to support this scenario right now because it's outside of our workflow at SmartyStreets. I wouldn't be opposed to someone making it happen via pull request though.

**Comment by leeola** [comment]
My only question then, i guess, is why https://github.com/smartystreets/goconvey/commit/cbae630b709dcb8761726f27948aab4c125577ff seems to be working just fine for me? I figured there are ~two possible explanations:

1. There is a GoConvey error occurring on my system that is not immediately evident with basic/normal usage.
2. The `probableSymlinkError` checks are throwing errors in cases where they don't need to be. Such as in my case.

I've been using this same workflow for months, with no issues from GoConvey. This feels like an introduced bug. Thoughts?

**Comment by leeola** [comment]
For clarity, the error from GoConvey is as follows:

```
Please run goconvey from within your $GOPATH (symlinks might be problematic). Output and Error:  can't load package: package /full/path/to/project: import "/full/path/to/project": cannot import absolute path
```
