### ISSUE TITLE
Needs quiet mode

### ISSUE THREAD

**Issue by filmil** [smartystreets/goconvey#302]
It would be very good for goconvey to have a "quiet" mode.  That is, it should swallow and hide any passing tests, and only report on what has failed.  

It is indeed pretty to watch things turning green as you look at http://localhost:8080 or go test . output, but it is not necessary.

If all systems are nominal I'd just like to see a single 'ok', or a single green button.

**Comment by mdwhatcott** [comment]
For testing in the console try this:

    go test -silent

That flag is defined in the [`convey`](http://godoc.org/github.com/smartystreets/goconvey/convey) package so it will only work on packages that `import "github.com/smartystreets/goconvey/convey"`.

To make quiet mode happen in the UI would take a bit more work. A new setting in the UI would be acceptable if you or someone else is willing to make that happen.

**Comment by mdwhatcott** [comment]
Also, you can make all packages appear collapsed by default, this would cut down on the "noise" significantly.

**Comment by filmil** [comment]
On Thu Feb 05 2015 at 7:40:56 AM Michael Whatcott <notifications@github.com>
wrote:

> Also, you can make all packages appear collapsed by default, this would
> cut down on the "noise" significantly.
>
IMHO, actual quiet mode is better.  I only realy care about things that
don't go as expected. Sometimes I almost get a heart attack seeing red
builds, so not tickling that note for me would be great. :)

>

**Comment by jalan** [comment]
Since this is the top hit for Google searches of "goconvey quiet" and "goconvey silent", adding a note here that the flag mentioned above got renamed. It is now

```
go test -convey-silent
```
