### ISSUE TITLE
src in GOPATH

### ISSUE THREAD

**Issue by craigjackson** [smartystreets/goconvey#303]
If you have a directory called "src" in your GOPATH (i.e. GOPATH=/home/craig/src/gopath), it will incorrectly resolve the package name during the web server initialization.

It looks like the culprit is the use of strings.Index searching for first use of "/src/" in package path. If "src" is in GOPATH, that will match instead of the "src" directory directly after the GOPATH.

```go
func resolvePackageName(path string) string {
  index := strings.Index(path, endGoPath)
  if index < 0 {
    return path
  }
  packageBeginning := index + len(endGoPath)
  name := path[packageBeginning:]
  return name
}
const (
  separator = string(filepath.Separator)
  endGoPath = separator + "src" + separator
)
```

Resolution for the time being is to not have a "src" directory in the GOPATH for the package.

EDIT: Grammar fixes

**Comment by mdwhatcott** [comment]
Yeah, good point. A correct implementation would probably use [build.ImportDir](http://golang.org/pkg/go/build/#ImportDir).
