### ISSUE TITLE
.message Font Fails to Render "Fi" Characters

### ISSUE THREAD

**Issue by andrewaustin** [smartystreets/goconvey#304]
I'm on Ubuntu 14.04 LTS running Firefox 35.

When I do a fmt.Println and that is rendered in the web UI, the fi characters are rendered as a dot instead of an "fi".

![goconveyerror](https://cloud.githubusercontent.com/assets/166746/5805203/ce3d61d2-9fda-11e4-8dae-4e36df549514.png)

This seems to be an issue with the styling of ``.story-line-desc .message``:

```
font-family: "Menlo","Share Tech Mono",monospace;
````

Removing "Share Tech Mono" style seems to fix the issue, but I wasn't sure how it would affect other platforms.

**Comment by mdwhatcott** [comment]
It probably wouldn't be the end of the world to not have that particular font in the lineup.
