### ISSUE TITLE
Duplicated directories looking for a package

### ISSUE THREAD

**Issue by theclapp** [smartystreets/goconvey#306]
Running goconvey on a Windows 7 box, I get this error:

can't load package: package goget/src/github.com/gophergala/panopticon/server: cannot find package "goget/src/github.com/gophergala/panopticon/server" in any of:
	C:\Go\src\goget\src\github.com\gophergala\panopticon\server (from $GOROOT)
	c:\Users\lmc\src\goget\src\goget\src\github.com\gophergala\panopticon\server (from $GOPATH)

I am in C:\Users\lmc\src\goget\src\github.com\gophergala\panopticon\server and that's where I run goconvey from.
GOPATH is C:\Users\lmc\src\goget

I'm not sure why, but goconvey apparently tries to put an extra "goget\src" into the path it's looking for.

Running goconvey in its own directory has similar results:

 BUILD FAILURES
  goget\src\github.com\smartystreets\goconvey\examples
can't load package: package goget/src/github.com/smartystreets/goconvey/examples: cannot find package "goget/src/github.com/smartystreets/goconvey/examples" in any of:
	C:\Go\src\goget\src\github.com\smartystreets\goconvey\examples (from $GOROOT)
	c:\Users\lmc\src\goget\src\goget\src\github.com\smartystreets\goconvey\examples (from $GOPATH)

**Comment by theclapp** [comment]
I got this to work by setting my GOPATH to `C:/Users/lmc/src/goget;c:/Users/lmc`.

Without knowing anything more, I'd consider this a workaround, not a fix.  FWIW.

**Comment by mdwhatcott** [comment]
I'm pretty sure your issue is related to #303. But it could also be specific to windows. We don't do any go development in windows so I'm not as confident about GoConvey's performance there.

**Comment by theclapp** [comment]
> I'm pretty sure your issue is related to #303

That seems likely.  Thanks.
