### ISSUE TITLE
goconvey fails but go test succeeds

### ISSUE THREAD

**Issue by gummybears** [smartystreets/goconvey#308]
Using go version 1.4, Ubuntu 12.04, latest goconvey using ginkgo
When running my tests as 
```
$ go test
Running Suite: Config Suite
===========================
Random Seed: 1422793604
Will run 14 of 14 specs

••••••••••••••
Ran 14 of 14 Specs in 0.022 seconds
SUCCESS! -- 14 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```
but running them via goconvey in the GUI gives me a fail. 
```
Running Suite: Config Suite
===========================
Random Seed: [1m1422793478[0m
Will run [1m14[0m of [1m14[0m specs

[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m[32m•[0m
[1m[32mRan 14 of 14 Specs in 0.046 seconds[0m
[1m[32mSUCCESS![0m -- [32m[1m14 Passed[0m | [91m[1m0 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m --- PASS: TestConfig (0.05s
```
I think it has to do with the colored terminal output. The terminal is set to xterm.

**Comment by mdwhatcott** [comment]
I think there's an open pull request to fix this: https://github.com/smartystreets/goconvey/pull/272

Can you check that out and see if it resolves the issue? If so, I'll expedite clicking the "merge" button.

**Comment by gummybears** [comment]
Did check out #272, from what I understand it fixes the issue. Perhaps best is to merge #272.

**Comment by mdwhatcott** [comment]
#272 is now merged.
