### ISSUE TITLE
Ignoring packages should not trigger re-run

### ISSUE THREAD

**Issue by tchajed** [smartystreets/goconvey#310]
Sometimes I want to ignore a bunch of packages to speed up test execution while focusing on one part of the codebase. Unfortunately, each package I ignore triggers a re-run of the tests, even if I pause the tests, which means I have to wait for goconvey to stop re-running tests.

I'd be happy to fix this myself but wanted to document the issue first and get feedback on this behavior.

**Comment by mdwhatcott** [comment]
I actually can't remember my reasoning for re-running tests whenever a package is ignored. I don't have a problem with the change you are proposing. Anyone else have any strong feelings?

As far as implementing this goes, it would simply require removing the calls to `this.execute()` in the [respond()](https://github.com/smartystreets/goconvey/blob/master/web/server/watch/integration.go#L64) function (and deleting the execute function as it's not called from anywhere else).

**Comment by tchajed** [comment]
I think what I'd like is:
* `messaging.WatcherIgnore` should not call execute
* `messaging.WatcherReinstate` should call execute only if `!this.paused`.

Thanks for pointing to the exact code, I can quickly make a pull request once we decide what to do.

**Comment by mdwhatcott** [comment]
Good point, reinstating a package should cause tests to execute.

**Comment by tchajed** [comment]
There's one minor complication (more fully discussed in #311): to prevent the watcher from re-running due to a new number of watched folders, you have to re-compute the checksum, which makes the tests not to see a watch event for the ignore.

**Comment by mdwhatcott** [comment]
What if (for the sake of simplicity) the only events that ever triggered test execution were file system events, the user clicking the "execute" button on the UI, and the user changing the root path? That would mean that pause, resume, ignore and reinstate would not trigger test execution. Which would be worse: every action causing re-execution of tests or almost none of them doing so?

**Comment by tchajed** [comment]
I like that a lot better. There's nothing you can do once execution starts except wait, while if it doesn't run when you want it to you can always click the execute button. This was particularly a problem for me on a slow laptop where our test suite took 30s, which made goconvey almost unusable.

I'll update the pull request and tests over the weekend.

**Comment by mdwhatcott** [comment]
Is the pull request ready to roll? I'll merge as soon as I hear from you.

**Comment by tchajed** [comment]
Yes, it's good to go. Thanks!
