### ISSUE TITLE
ATTENTION: GoConvey maintainers wanted!

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/goconvey#329]
We'd like to open the project up to additional maintainers who want to move the project forward in a meaningful way.

We've spent significant time at SmartyStreets building GoConvey and it has perfectly met (and exceeded) all of our initial design specifications. We've used it to great effect. Being so well-matched to our development workflows at SmartyStreets, we haven't had a need to hack on it lately. This had been frustrating to many in the community who have ideas for the project and would like to see new features released (and some old bugs fixed). The release of Go 1.5 and the new vendoring experiment has been a source of confusion and hassle for those who have already upgraded and find that GoConvey needs to be brought up to speed.

Comment below if you're interested. Preference will be given to those that have already contributed to the project. Checkout the issues listing if you need some ideas for contributing.

GoConvey is a popular 2-pronged, open-source github project (1,600+ stargazers, 100+ forks):

- A package you import in your test code that allows you to write BDD-style tests.
- An executable that runs a local web server which displays auto-updating test results in a web browser.

http://goconvey.co/
https://github.com/smartystreets/goconvey
https://github.com/smartystreets/goconvey/wiki

_I should mention that the [assertions package](https://github.com/smartystreets/assertions) imported by the convey package is used by other projects at SmartyStreets and so we will be continuing to maintain that project internally._

We hope to hear from you soon. Thanks!

**Comment by mdwhatcott** [comment]
Top 3 contributors:

@mholt
@riannucci 
@m4rw3r 

Any of you interested in being a maintainer? @mholt: maybe this is your chance to extend GoConvey into a full-fledged go tool gui?

**Comment by riannucci** [comment]
Haha... welll.... I'm still vaguely interested in finishing the test parallelization/randomization stuff, but it would require some gui work (that I'm definitely not up to snuff on... peasant backend programmer here :smile:). I'm definitely still getting a lot of use out of goconvey though, so I'd be sad to see it fade to black.

I'm definitely up for doing code reviews, etc. but I'm not sure I'd be able to devote enough time to direct the development of much, if that makes sense.

I have also wondered if it might make sense to split the convey and webserver portions of the project (by defining a test<->UI protocol). Would that help for maintainability? I definitely am more familiar with the convey side than the webapp side, for example.

**Comment by mdwhatcott** [comment]
@riannucci - I think splitting the project would ease maintainability (they probably should have been separate projects from the beginning). Maybe create a new issue where that idea can be fleshed out?

**Comment by riannucci** [comment]
Done :)

**Comment by tobz** [comment]
Some high level questions:

- Can/does goconvey dogfood itself to any extent?  How much can contributors hope to lean on existing tests to ensure they aren't breaking things?
- Does it make sense to move the code to a neutral GitHub organization?  I'm not sure how much SmartyStreets cares about company-level attribution but it seems like distributed governance/contributing would be a little shaky ground-esque if a company owns the code but doesn't actively contribute.

**Comment by mdwhatcott** [comment]
@tobz - 

Regarding question 1 (above): the GoConvey project has a pretty rigorous test suite. The tests for the library (everything under the `convey` package) were written using the standard go "testing" package. Everything under "web/server" is under test using the `convey` package. There are currently a few issues related to broken or skipped tests:

- [Broken Tests](https://github.com/smartystreets/goconvey/issues/328)
- [Skipped Tests](https://github.com/smartystreets/goconvey/issues/250)

Stay tuned for a more detailed answer to item 2 (above).

**Comment by mdwhatcott** [comment]
@tobz - Regarding question 2 (above): before moving the project to a neutral Github organization we'd like to see that the community has rallied around the project and really is taking it somewhere meaningful. So, let's keep the idea in mind.

**Comment by VorT3x** [comment]
@mdwhatcott it looks like there are not so many people who want to maintain GoConvey. I would like to help!

**Comment by mholt** [comment]
@mdwhatcott It is a great opportunity but I don't have the time right now :( (Hopefully somebody else will one day.)

**Comment by mdwhatcott** [comment]
@VorT3x - Thanks for getting involved in the project! We've noted your interest and will be in contact with you as decisions are made.

**Comment by vladdy** [comment]
I would also be interested in participating in maintenance, if the decision has not been made yet.

**Comment by mdwhatcott** [comment]
@vladdy - Noted.

**Comment by mdwhatcott** [comment]
@mholt @riannucci @VorT3x @vladdy @tobz @onlyjob @ruzz311 @e-max 

It's been a while since I first opened this issue. Since then I've continued to maintain GoConvey by responding to critical issues and merging pull requests. There appears to be plenty of interest in this project and just in the last week there has been a lot of activity.

Each of you has either had significant involvement in the past or very recent involvement with GoConvey. Because of your contributions **SmartyStreets is now ready to add collaborators to the project from any among you who are interested in maintaining the project moving forward**. GoConvey will remain on the SmartyStreets github organization for the foreseeable future. I will remain available as a resource when there are questions about design choices or the implementation but will no longer be approving/closing pull requests or actively dealing with issues.

GoConvey is an awesome project with a sizable following and still a lot of potential. Let me know in additional comments if you are interested in becoming a maintainer/collaborator. Thanks for all your contributions thus far!

Mike

**Comment by riannucci** [comment]
Okie dokie... What would the triage process for PRs/code reviews look like, or is that TBD?

**Comment by ruzz311** [comment]
I don't mind poking through the issues.  I'm not as familiar with the code but I don't mind digging into it a bit.

**Comment by mdwhatcott** [comment]
@riannucci The new maintainers would need to work that out. Basically, we are bowing out and hoping that the community will rally around the project and carry it forward without much (if any) supervision or intervention from the SmartyStreets team. Are you in?

**Comment by mdwhatcott** [comment]
@ruzz311 - There would, of course, be a learning curve for the maintainers. I would be available when questions come up.

**Comment by mdwhatcott** [comment]
In response to the last question from @riannucci about triaging issues and pull requests, feel free to post proposals for how you think things could/should work.

**Comment by riannucci** [comment]
Ah ok.

Well it looks like there's about 40 open issues right now. What's the general volume of issues/week?

**Comment by mdwhatcott** [comment]
Generally between 2 and 5 new issues opened per week. Some of them are closed quickly (docs weren't helpful enough or just user error).

**Comment by VorT3x** [comment]
@mdwhatcott do you use Trello board for GoConvey? Or at least google group for communications?

But I still would like to help with GoConvey.

**Comment by mdwhatcott** [comment]
No, not right now.

**Comment by mdwhatcott** [comment]
So far I've added the following as collaborators with write access:

- @ruzz311 
- @e-max 
- @riannucci 
- @VorT3x 
- @vladdy 

If any of you have had second thoughts and want to be removed from the list, let me know. Likewise, if I've missed out on anyone that wants to help, just leave a comment asking to be included.

**Comment by pickhardt** [comment]
Is this project still looking for a lead maintainer?

**Comment by mdwhatcott** [comment]
Not necessarily a lead maintainer, but if you're interested in helping out and would eventually like commit privileges feel free to dig into the current issues. (If I'm behind the times and you've already been hard at work, let me know and we'll get you added.)
