### ISSUE TITLE
Goconvey does not launch browser in Windows/Linux

### ISSUE THREAD

**Issue by wallclockbuilder** [smartystreets/goconvey#337]
Goconvey opens conveniently opens browser when launched in OSX. See PR #336 

PRs needed to replicate in Windows/Linux.

Ideally the person implementing is running the target OS and thus can verify that the implementation works.

**Comment by VorT3x** [comment]
Fixed. https://github.com/wallclockbuilder/goconvey/commit/e5e588cc56114f9fb4efca435392e4ea44e24f3d

**Comment by wallclockbuilder** [comment]
ACK.
Closing issue.
