### ISSUE TITLE
Recursively ignore folders

### ISSUE THREAD

**Issue by pjoe** [smartystreets/goconvey#345]
I know that are profiles that can ignore individual packages, but they do not recursively ignore.

My use case has the following reasons for a better way to ignore folders (something like .gitignore):
- Using go 1.5 vendoring (i.e. vendoring to a vendor folder, which I want to be able to ignore)
- Having frontend stuff using bower and node also creates subfolders with tons of stuff (bower_components and node_modules) that there is no reason for goconvey to traverse

**Comment by mdwhatcott** [comment]
Great points. Your use case is becoming more and more common amongst goconvey users. Maybe this could be implemented as an extension of the currently supported profiles?

**Comment by pjoe** [comment]
Possibly :)

I would prefer if the ignore setting can be done in the parent folder (maybe in it's profile), as e.g. for bower_components and node_modules I sometimes end up removing both folders and reinstalling those - which would break if their ignore settings were inside.

**Comment by pjoe** [comment]
I will try taking a quick look, which branch do you prefer PR's against, master?

**Comment by mdwhatcott** [comment]
That would be fine.

**Comment by brocaar** [comment]
Would it make sense to add the possibility to specify a list of packages to the ``goconvey`` cli tool? This would be in line with the ``go test`` command. To work around the issue of the ``vendor/`` folder, e.g. I'm currently using ``go test `go list ./... | grep -v /vendor/``` to run my tests and ignore the vendored packages.

**Comment by mdwhatcott** [comment]
@brocaar - yes, that's one way to go about it and it could work. Keep in mind that the web UI allows you to move the runner around to different directories (by editing the path near the top of the screen). Would the list of packages follow the runner to different file system locations?

**Comment by thomasmodeneis** [comment]
Hi, @brocaar  thanks for the tip, does this works as well for the WEB runner ?

Cheers.

**Comment by brocaar** [comment]
The problem (I realise now) is that the web ui expects a path, rather than a list of packages as ``go test`` does. I think when mixing these two concepts together in goconvey, things might get a bit complex to grasp / overcomplicate things.

**Comment by Keats** [comment]
Anyone using goconvey with gb successfully?

**Comment by mdwhatcott** [comment]
Yeah, that's a creative workaround. (It would break down if your project has several layers of nested packages/folders, hence the need for something better.)

**Comment by vrecan** [comment]
this issue seems to be biting me as well, I am using go 1.5 vendoring and goconvey tends to lock up.

**Comment by meAmidos** [comment]
I have just encountered the same issue. There is a temporary solution:

```
cd myproject
goconvey -depth=1
```

However, something more general is needed to address the issue completely.

**Comment by DallanQ** [comment]
It appears that this has been addressed by f1f43eca0762bb2318cdda9019d1b510fedd66b3 - is that correct?

**Comment by mdwhatcott** [comment]
Yes, it would seem @DallanQ. Can you confirm @pjoe ?

**Comment by pjoe** [comment]
@mdwhatcott: seems to be working for me, though I would suggest also adding `bower_components` to the default

**Comment by mdwhatcott** [comment]
@pjoe - Anyone is welcome to submit that as a default in a separate PR.

I'll close the issue then. Feel free to re-open if there are continuing issues.
