### ISSUE TITLE
'ShouldEqual' should panic when trying to compare different types

### ISSUE THREAD

**Issue by mattwarren1234** [smartystreets/goconvey#348]
The below example should panic:
```
So("2", ShouldEqual, 2)
```
Instead it displays the following message (test fails, for seemingly no reason):
![image](https://cloud.githubusercontent.com/assets/6097694/9972280/f33f389c-5e17-11e5-91d6-2342eabccb1c.png)

**Comment by mdwhatcott** [comment]
Thanks for bringing this to my attention.

_Note to self: This is actually an issue with the [assertions](https://github.com/smartystreets/assertions) package, not the GoConvey project._

Hmm, I disagree with the idea that the assertions package or even the convey package should panic in a failure scenario. I would say we just need more helpful error message. Something like:

```
Expected: '2' (string)
Actual:   '2' (int)
(Should be equal)
```

Keep in mind that you can currently compare the `int` value 2 with the `int64` value 2 without any problems. I wouldn't want to disrupt that behavior.

I'll take a look at this.

**Comment by mattwarren1234** [comment]
Yeah, listing types would be even more helpful!

**Comment by mdwhatcott** [comment]
Pull the latest:

```
go get -u github.com/smartystreets/assertions
```
