### ISSUE TITLE
Unreachable code in test. Does it make sense to keep it?

### ISSUE THREAD

**Issue by alebaffa** [smartystreets/goconvey#353]
There is some unreachable code in the test *isolated_execution_test.go*. The variable *output* after the call to panic() will never be executed. Does it make sense to keep it?
There are three cases like this.

	Convey("This is the parent", t, func() {
		Convey("This step panics", func() {
			panic("Hi")
			output += "1"
		})

**Comment by mdwhatcott** [comment]
The unreachable code serves to illustrate what should and should not be executed in situations where the production code panics. I think it is appropriate for the unreachable statements to remain in the code, even though tools like go vet will complain.

**Comment by alebaffa** [comment]
OK. Makes sense :+1: Thanks.
