### ISSUE TITLE
how do I exclude the 'vendor' directory (or any directory really).

### ISSUE THREAD

**Issue by luck02** [smartystreets/goconvey#354]
I'm using go1.5 vendoring features, I don't want goconvey to run all the vendored dependancies code if I can avoid it.  I don't see a command line flag to exclude a specific directory.

Thoughts?

**Comment by luck02** [comment]
found a workaround, there is a 'depth' command, when set to a level that prevents descending into vendor/** directories but still hitting project directories we seem to have a functional implementation with /vendor/**

**Comment by mdwhatcott** [comment]
See discussion on issue #345

**Comment by thomasmodeneis** [comment]
Hi,
Sorry but this ticket was closed and the reference given is the same ticket.

I'm also interested to get this exclusion, could you please reference the correct link or maybe what was the fix for this ??

Thanks
