### ISSUE TITLE
Outdated cover tool error message

### ISSUE THREAD

**Issue by Thomasdezeeuw** [smartystreets/goconvey#356]
The following line: https://github.com/smartystreets/goconvey/blob/aa2f5dd3546751f4d6be93cb58e906023324664c/goconvey.go#L275, points to `golang.org/x/tools/cmd/cover` to install the cover tool. However since Go 1.5, it's been deprecated and has moved to the main repository in `/src/cmd/cover`. People need to run `go install` from their and it works just fine.

**Comment by mdwhatcott** [comment]
That's great--I hadn't realized that. Are you up for correcting that in a pull request?

**Comment by Thomasdezeeuw** [comment]
Is something like this ok? 
```Go cover tool is not installed or not accessible: for Go < 1.5  run`go get golang.org/x/tools/cmd/cover`\n
For > Go 1.5 run `go install $GOROOT/src/cmd/cover`\n```

**Comment by mdwhatcott** [comment]
```
Go cover tool is not installed or not accessible: for Go < 1.5 run`go get golang.org/x/tools/cmd/cover`\n For >= Go 1.5 run `go install $GOROOT/src/cmd/cover`\n
```

(changed `>` to `>=`)

That looks good.
