### ISSUE TITLE
Site goconvey.co not working

### ISSUE THREAD

**Issue by 2tvenom** [smartystreets/goconvey#359]
Please check your domain

**Comment by mdwhatcott** [comment]
Fixed.

**Comment by mdwhatcott** [comment]
Should be working now...

**Comment by 2tvenom** [comment]
still 400 bar request

**Comment by mdwhatcott** [comment]
Yeah, every time I think it's working it stops. Not happy with namecheap at the moment...

**Comment by mdwhatcott** [comment]
ok, try it now <holding-breath>.

**Comment by 2tvenom** [comment]
working
thank you
