### ISSUE TITLE
source-less minified javascripts

### ISSUE THREAD

**Issue by onlyjob** [smartystreets/goconvey#363]
`web/client` contains source-less minified javascripts. Effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in Debian.
It is a bad practice to commit binaries to VCS. 
Please replace all minified files with their original (non-minified) sources.

Read more in https://wiki.debian.org/onlyjob/no-minification

Thanks.

**Comment by mdwhatcott** [comment]
Distributing GoConvey as a debian package was actually never part of the original (or current) intent of the project. All that means is that there is little chance of someone within smartystreets doing anything about this issue. A pull request from the community would be welcome.

**Comment by onlyjob** [comment]
Let alone Debian compliance, I'm not asking to distribute GoConvey as package.  I merely point out what could be improved from best practice prospective. Un-minification of bundled javascripts have benefits of its own, unrelated to packaging.

**Comment by mdwhatcott** [comment]
Feel free to make the modifications you are suggesting.

**Comment by onlyjob** [comment]
This problem is not (completely) fixed by #392.
There is `font-awesome.min.css` and `jquery-ui-1_10_3-custom.min.js` but I do not know how the latter was generated. Maybe switch to standard (not custom) build?

Please reopen.

**Comment by onlyjob** [comment]
Thanks. Any ideas how to get the same jquery-ui? What are the build options?

**Comment by mdwhatcott** [comment]
I'm not sure how it was built. The only thing I can think to do is experiment by building jquery-ui a few different ways and see which one works the best.

**Comment by onlyjob** [comment]
Well, we will have benefits of reproducible build when someone figure that out. :)

**Comment by onlyjob** [comment]
May I ask you to release 1.6.1 with those changes please so it could be packaged? Thank you.

**Comment by mdwhatcott** [comment]
Done.

**Comment by onlyjob** [comment]
Thank you very much. Very helpful.

**Comment by onlyjob** [comment]
@mdwhatcott, we need another correction: #395. This is because new "font-awesome" replaced customised CSS file that broke relative path to font files. #395 restores upstream folder structure of _font-awesome_ so it should be easier to update in the future. Once #395 is merged it would be great if you could do another release bump please.
Thanks and sorry for troubles.
