### ISSUE TITLE
Current Best-Practice for Table-Like tests?

### ISSUE THREAD

**Issue by EmergentBehavior** [smartystreets/goconvey#364]
I've reviewed several issues here referring directly or indirectly to table-driven tests and issues associated with using them in the context of GoConvey. Is there a currently accept "best practice" for using them here? Or, is there another way to achieve a similar outcome (i.e. run our tests against varying initial conditions)?

**Comment by mdwhatcott** [comment]
Table-driven testing is supported by the `convey` package. Try to keep things simple, something like this:

```go

var cases = []struct{
    description ...
    input ...
    expected ...
} {
    // test case instances
}

Convey("Explain what'g going on...", t, func() {
    // initial setup
    for _, test := range cases {
        // test case setup
        Convey("Something about: " + test.description, func() {
            // invoke action being tested with inputs from test case (x.input)
            So(...) // compare results against expected result (x.expected)
        })
    }
})
```

Or, you can just do traditional table-driven testing without the `convey` package. Whatever feels most simple and straightforward.

Hope that helps. Feel free to elaborate if I missed the mark.

**Comment by EmergentBehavior** [comment]
Awesome -- so seems key is just minimize the nesting. Thanks!
