### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by brianvoe** [smartystreets/goconvey#367]
Just upgraded to 1.5.1 and goconvey stopped working. Also your travis build is failing too.

2015/11/20 21:21:55 goconvey.go:56: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2015/11/20 21:21:55 tester.go:19: Now configured to test 10 packages concurrently.
2015/11/20 21:21:55 goconvey.go:138: Serving HTTP at: http://127.0.0.1:8080
2015/11/20 21:21:55 integration.go:120: File system state modified, publishing current folders... 0 61690644024
2015/11/20 21:21:55 goconvey.go:85: Received request from watcher to execute tests...
2015/11/20 21:21:55 executor.go:69: Executor status: 'executing'
2015/11/20 21:21:55 coordinator.go:46: Executing concurrent tests: github.com/brianvoe/gofakeit
2015/11/20 21:21:56 executor.go:69: Executor status: 'idle'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x4fbd68]

goroutine 18 [running]:
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).recordTestMetadata(0xc82005e070)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:105 +0x188
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).processTestOutput(0xc82005e070)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:85 +0x16e
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).separateTestFunctionsAndMetadata(0xc82005e070)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:53 +0xc1
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).parse(0xc82005e070)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:44 +0x21
github.com/smartystreets/goconvey/web/server/parser.ParsePackageResults(0xc8202da780, 0xc8200c9500, 0x134a)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:18 +0x43
github.com/smartystreets/goconvey/web/server/parser.(*Parser).Parse(0xc8200d2008, 0xc82011a570, 0x1, 0x1)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/parser/parser.go:16 +0x129
github.com/smartystreets/goconvey/web/server/executor.(*Executor).parse(0xc8200dc100, 0xc82011a570, 0x1, 0x1, 0x9e7d00)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:47 +0x133
github.com/smartystreets/goconvey/web/server/executor.(*Executor).ExecuteTests(0xc8200dc100, 0xc82011a570, 0x1, 0x1, 0x0)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:36 +0x9f
main.runTestOnUpdates(0xc8200d80c0, 0x7f45c32a50a8, 0xc8200dc100, 0x7f45c32a50e0, 0xc8200dc140)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/goconvey.go:93 +0x323
created by main.main
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/goconvey.go:78 +0x9a8

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f45c2a64fd8, 0x72, 0xc82000a200)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820106060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820106060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820106000, 0x0, 0x7f45c2a650d0, 0xc820108040)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82010c000, 0xc8200c7a20, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82010c000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820100000, 0x7f45c2a65098, 0xc82010c000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820100000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc8200fc030, 0xe, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1967 +0x8f
main.activateServer()
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/goconvey.go:139 +0x2b9
main.serveHTTP(0x7f45c32a50e0, 0xc8200dc140)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/goconvey.go:119 +0x35
main.main()
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/goconvey.go:80 +0xa0e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [sleep]:
time.Sleep(0xee6b280)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/smartystreets/goconvey/web/server/watch.(*Watcher).Listen(0xc8200e0000)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/watch/integration.go:59 +0xcc
created by main.main
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/goconvey.go:79 +0x9ca

goroutine 24 [runnable]:
syscall.ByteSliceFromString(0xc820010180, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall.go:53 +0x126
syscall.BytePtrFromString(0xc820010180, 0x3b, 0xc820439180, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall.go:69 +0x3b
syscall.SlicePtrFromStrings(0xc82000c800, 0x3e, 0x3e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:87 +0xd6
syscall.forkExec(0xc8204c8ce0, 0x14, 0xc8202dbe60, 0x6, 0x6, 0xc820040b60, 0xc82043aab0, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:158 +0x1d0
syscall.StartProcess(0xc8204c8ce0, 0x14, 0xc8202dbe60, 0x6, 0x6, 0xc820040b60, 0x2, 0x4, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x6b
os.startProcess(0xc8204c8ce0, 0x14, 0xc8202dbe60, 0x6, 0x6, 0xc820040d98, 0xc82000c800, 0x0, 0x0)
	/usr/local/go/src/os/exec_posix.go:45 +0x33c
os.StartProcess(0xc8204c8ce0, 0x14, 0xc8202dbe60, 0x6, 0x6, 0xc820040d98, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:24 +0x69
os/exec.(*Cmd).Start(0xc82030e140, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:328 +0x767
os/exec.(*Cmd).Run(0xc82030e140, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:255 +0x2d
os/exec.(*Cmd).CombinedOutput(0xc82030e140, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:424 +0x310
github.com/smartystreets/goconvey/web/server/system.Command.Execute(0xc820010104, 0x3a, 0x809910, 0x2, 0xc8201c0190, 0x5, 0x5, 0x0, 0x0, 0x0, ...)
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/system/shell.go:164 +0x100
created by github.com/smartystreets/goconvey/web/server/system.(*Shell).GoTest
	/home/brianvoe/Desktop/go/src/github.com/smartystreets/goconvey/web/server/system/shell.go:42 +0x784

**Comment by mdwhatcott** [comment]
Did you run `go install github.com/smartystreets/goconvey` after upgrading your go installation? @brianvoe

**Comment by brianvoe** [comment]
Yes

**Comment by mdwhatcott** [comment]
What commit is your goconvey repository set to?

I'm at the latest (530dd3d).

Here's what I get when I run `goconvey` on your repository:

```
mike@Michael:~/src/github.com/brianvoe/gofakeit [master]

 • goconvey
2015/11/20 21:33:24 goconvey.go:58: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2015/11/20 21:33:24 tester.go:19: Now configured to test 10 packages concurrently.
2015/11/20 21:33:24 goconvey.go:174: Serving HTTP at: http://127.0.0.1:8080
2015/11/20 21:33:24 goconvey.go:98: Launching browser on 127.0.0.1:8080
2015/11/20 21:33:24 integration.go:120: File system state modified, publishing current folders... 0 62267568557
2015/11/20 21:33:24 goconvey.go:111: Received request from watcher to execute tests...
2015/11/20 21:33:24 executor.go:69: Executor status: 'executing'
2015/11/20 21:33:24 coordinator.go:46: Executing concurrent tests: github.com/brianvoe/gofakeit
2015/11/20 21:33:24 goconvey.go:106: 
2015/11/20 21:33:25 parser.go:24: [failed]: github.com/brianvoe/gofakeit
2015/11/20 21:33:25 executor.go:69: Executor status: 'idle'
2015/11/20 21:33:34 integration.go:95: Gathering folders for immediate execution...
2015/11/20 21:33:34 goconvey.go:111: Received request from watcher to execute tests...
2015/11/20 21:33:34 executor.go:69: Executor status: 'executing'
2015/11/20 21:33:34 coordinator.go:46: Executing concurrent tests: github.com/brianvoe/gofakeit
2015/11/20 21:33:35 parser.go:24: [failed]: github.com/brianvoe/gofakeit
2015/11/20 21:33:35 executor.go:69: Executor status: 'idle'

```

Basically, everything works fine. I don't doubt that you're experiencing a problem/bug but at this point I'm not sure how to reproduce it.

**Comment by brianvoe** [comment]
Looks like i got it working again. I completely removed the bin install and the src. reran go get and go install and it works perfectly now. Thought it might have been cause of the travis build fail.

Love this package!!! Let me know if there is any simple way i can contribute.

**Comment by mdwhatcott** [comment]
I don't quite understand why you have to totally clean it out after the go 1.5 update but you're not alone in having to do so.

Feel free to take a look at the open issues and my recent commits in which I marked a few broken tests as skipped. They worked before go 1.5 but obviously the logic wasn't sound as it was dependent on previous implementation details of the go runtime.

**Comment by mdwhatcott** [comment]
Glad you've enjoyed using the package!

**Comment by Rogerzhao** [comment]
2017/01/22 10:46:28 executor.go:69: Executor status: 'idle'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x5381d8]

goroutine 6 [running]:
panic(0x7fa640, 0xc8200100c0)

**Comment by Rogerzhao** [comment]
Hello @mdwhatcott , Do you reproduce the problem ? and have it fixed ?

**Comment by mdwhatcott** [comment]
@Rogerzhao - No, I haven't worked on this issue for some time.

**Comment by Rogerzhao** [comment]
Actually this one exist. For all the time ,I try goconey command.
Anyone I can ask help from please.
