### ISSUE TITLE
assertion failures with indistinguishable diagnostic output

### ISSUE THREAD

**Issue by jxstanford** [smartystreets/goconvey#369]
I have the following set of assertions:

```
So(result.Items[0].ID, ShouldEqual, i2.ID)
So(result.Items[0].ETag, ShouldEqual, i2.ETag)
So(result.Items[0].Payload["id"], ShouldEqual, i2.Payload["id"])
So(result.Items[0].Payload["f1"], ShouldEqual, i2.Payload["f1"])
So(result.Items[0].Payload["f2"], ShouldEqual, i2.Payload["f2"])
So(result.Items[0].Updated, ShouldHaveSameTypeAs, i2.Updated)
// So(result.Items[0].Updated, ShouldEqual, i2.Updated)
// So(result.Items[0].Payload, ShouldResemble, i2.Payload)
```

Updated is a time.Time and Payload is a map[string]interface{}.

All of the uncommented assertions pass, but the commented out ones fail.  The ShouldEqual for the Updated field returns:

```
Expected: '2015-12-03 23:04:26.773272321 -0800 PST'
Actual:   '2015-12-03 23:04:26.773272321 -0800 PST'
(Should be equal)
```

The ShouldResemble for the Payload field returns:

```
Expected: 'map[string]interface {}{"id":"7a15f07f-2610-47ca-ac3d-884a0081c1fc", "f1":"bar", "f2":2}' (map[string]interface {})
Actual:   'map[string]interface {}{"id":"7a15f07f-2610-47ca-ac3d-884a0081c1fc", "f1":"bar", "f2":2}' (map[string]interface {})
(Should resemble, type mismatch)
```

In both cases the diagnostic output shows that they have the same string representation.  Am I misusing the assertions for these types?

**Comment by mdwhatcott** [comment]
You should use `ShouldResemble` to compare instances of `time.Time`.

As for comparing instances of `map[string]interface{}`, that will probably fail if the `interface{}` values are different types. There's an open pull request on the assertions package that might give better output in this failure scenario. You can check out the code for that pull request and re-run to see if that helps.

**Comment by jxstanford** [comment]
Time assertion working now.  I'll check out the code in the PR, and hopefully see it in the next release!  Thanks for the prompt reply.  Issue resolved from my perspective...
