### ISSUE TITLE
New formal release please?

### ISSUE THREAD

**Issue by onlyjob** [smartystreets/goconvey#372]
Latest [formal release](https://github.com/smartystreets/goconvey/releases) v1.5.0 dated almost two years ago and some libraries using _goconvey_ [moved on](https://github.com/go-ini/ini/issues/27) to unreleased snapshots. Please consider tagging new release. Thanks.

**Comment by mdwhatcott** [comment]
Done. https://github.com/smartystreets/goconvey/releases/tag/1.6.0

**Comment by onlyjob** [comment]
Awesome. Thank you.
