### ISSUE TITLE
Consider switching to x/net/context

### ISSUE THREAD

**Issue by flimzy** [smartystreets/goconvey#374]
I was recently introduced to GoConvey at a Golang meetup, and it looks quite promising for my current project. However, it's not quite working for me, due to the fact that my project is using [GopherJS](http://www.gopherjs.org/), which seems not to work with the [gls](https://github.com/jtolds/gls) package.

The README over at the [gls](https://github.com/jtolds/gls) project gives a big "warning" saying that the new(ish) [x/net/context](https://godoc.org/golang.org/x/net/context) package from Google now "solves all of the problems you'd perhaps consider using this package for at scale."

Certainly, that wasn't the case when the GoConvey project began.

I wonder if any thought has been given to the prospect of switching to this package.

GopherJS is is admittedly a bit of an edge case, and is known not to implement all of the minutiae of Go--especially when it comes to some aspects of reflection, which is clearly important to a package like this.  However, x/net/context does work with GopherJS.

Now, on the other hand, before anyone jumps off the deep end saying they'll quick, go port this thing to x/net/context, let me stress that I have not fully debugged this issue. It's possible that a small patch to either gls or GopherJS would solve my issue.  I'll investigate that when I have the time.

I'm simply posting this issue to ask if any thought has been put into this change, and perhaps it's already been rejected for valid reasons.  Or perhaps it's somebody's wish-list item, and something like this would make the transition more worth it.

Thoughts?

**Comment by mdwhatcott** [comment]
Using x/net/context instead of gls hasn't yet been suggested or considered. Feel free to investigate.

**Comment by flimzy** [comment]
Switching to x/net/context would require API changes, so it's probably not suitable for this project, except perhaps as a fork.

I've been working on a patch to make goconvey work with GopherJS, and that's proving quite a challenge as well, as the way Go handles the stack is of course entirely different from the way JS handles it. If I come up with such a patch, it will be against jtols/gls, too.

So I think this issue can be closed here for now.

**Comment by flimzy** [comment]
I have submitted a PR to jtolds/gls to add GopherJS support to this package, which allows GoConvey to be used with GopherJS.

https://github.com/jtolds/gls/pull/3

**Comment by jtolds** [comment]
[waves]

the downside with x/net/context is that one must pass a context argument to every call, everywhere on the stack. all function signatures must change. for goconvey's use, that might actually be somewhat challenging. it is certainly better, but it's quite a commitment.

**Comment by runner-mei** [comment]
please consider switching to context https://github.com/smartystreets/goconvey/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+gls+panic

a new tool to convert exists code?
