### ISSUE TITLE
Using native fs notifications

### ISSUE THREAD

**Issue by zhulik** [smartystreets/goconvey#380]
Hi, i suppose, using native OS events instead of timer polling in better and more pruductive. [This](https://github.com/howeyc/fsnotify) package provides  abstraction around platform dependent fs events for linux, macos, windows and bsd

**Comment by mdwhatcott** [comment]
I started out using fsnotify but in large projects there os often the problem of "too many open files".

See https://github.com/go-fsnotify/fsnotify/issues/9 for some of the history and discussion.
