### ISSUE TITLE
Goconvey keeps on re-testing

### ISSUE THREAD

**Issue by lionelmessi** [smartystreets/goconvey#383]
I have a `public` folder to serve static resources. I wrote tests to save static content in this folder using Convey.

It gets stuck in a never-ending loop due to the new files created in the public folder.

`integration.go:120: File system state modified, publishing current folders... 1452848214 1452848215`

How can I skip this folder? I tried adding `.goconvey` file to the folder with `ignore` but its not working. 

Any suggestions, how to skip watching that folder?

**Comment by mdwhatcott** [comment]
Try setting the `excludedDirs` flag: `goconvey -excludedDirs="public"`

https://github.com/smartystreets/goconvey/blob/master/goconvey.go#L44

**Comment by lionelmessi** [comment]
Thanks! I had an older version, looks like this change went in later :)
