### ISSUE TITLE
Code coverage not working endpoint API's test

### ISSUE THREAD

**Issue by lionelmessi** [smartystreets/goconvey#384]
I have written Convey tests for REST API for my server and kept those tests as separate as shown below.

   App
   -controllers
   -routers
   -tests

Similar to the tests below:
https://github.com/goinggo/beego-mgo/tree/master/test/endpointTests

The tests run and reports fine but the code coverage doesn't show anything. Is it possible to get the coverage as well?

**Comment by mdwhatcott** [comment]
Are the tests defined in the same package as the code you are invoking? If not, you won't see coverage from the GoConvey UI.

You can use the `-coverpkg` flag when running `go test` from the command line to get coverage information for other packages that your code calls.

**Comment by lionelmessi** [comment]
ok thanks!

**Comment by kounelios13** [comment]
> Are the tests defined in the same package as the code you are invoking? If not, you won't see coverage from the GoConvey UI.
> 
> You can use the `-coverpkg` flag when running `go test` from the command line to get coverage information for other packages that your code calls.

In case such as this is there a way to force convey ui to show the coverage using the -coverpkg flag?
