### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by yinqiang** [smartystreets/goconvey#385]
assertions.go:37: undefined: assertions.ShouldHaveLength

**Comment by keis** [comment]
Also just started seeing this and turns out something had put my goconvey to a version from a year back. Manually doing switching to the master branch solved this for me.

**Comment by mdwhatcott** [comment]
Make sure to run `go get -u github.com/smartystreets/assertions` to fetch the latest from that dependency.

**Comment by VorT3x** [comment]
@yinqiang it works fine now?
