### ISSUE TITLE
prefix for flags name

### ISSUE THREAD

**Issue by e-max** [smartystreets/goconvey#386]
Hi
GConvey added new flags to test command. (--story, --silent, --json).  
Could you consider adding some prefix to it?  Something like "test." prefix used by standard testing package.   I think "--gconvey.story" would be cool.  
Silent is quite common name for a flag and could conflict with application flags.

**Comment by mdwhatcott** [comment]
This is a good idea. Since these flags are meant to be internal I would be open to someone submitting a PR to modify the flag names as follows:

- `convey-story`
- `convey-silent`
- `convey-json`

**Comment by ruzz311** [comment]
@e-max @mdwhatcott - Can this issue be closed?

**Comment by e-max** [comment]
Yes, sure.

**Comment by mdwhatcott** [comment]
@ruzz311 or @e-max - Either one of you may close the issue as you now both collaborators on the project.
