### ISSUE TITLE
The ui shows first valid test result on startup only

### ISSUE THREAD

**Issue by dhf0820** [smartystreets/goconvey#388]
When I start the UI I get the one experimental test showing valid results.  If I change the test file to create a failure, the ui does not change. though I get the notice in top corner showing the proper failure.  THe ui never changes. I initially received several build failures. I discovered several uis running. When I stopped all but one it started responding.

**Comment by mdwhatcott** [comment]
Hmm, It's hard to say what might be going on. Can you post screenshots or a video somewhere? Or, is the code you are testing public? I'd love to try and recreate your scenario.

**Comment by dhf0820** [comment]
I fixed the problem in my code so not doing any more. I will watch for it though.  

One question.  It seems that only the test files are being monitored for change.  I can change the actual source and no trigger to run tests. I change the test file and it runs the tests.  I am using the structure of a separate test folder. That may not be the best way. Your suggestions?

Don French

**Comment by mdwhatcott** [comment]
Well, it should watch for changes in any .go file at or below the working directory where you launch goconvey.

https://github.com/smartystreets/goconvey/blob/master/goconvey.go#L43

**Comment by dhf0820** [comment]
Thank you. I was in the test folder

works great

**Comment by ruzz311** [comment]
@dhf0820 @mdwhatcott - Can this issue be closed?

**Comment by mdwhatcott** [comment]
Feel free to close the issue @ruzz311 (you're a collaborator now).

**Comment by dhf0820** [comment]
yes
