### ISSUE TITLE
Please Fix

### ISSUE THREAD

**Issue by devinceble** [smartystreets/goconvey#399]
https://github.com/smartystreets/goconvey/blob/master/web/client/resources/js/lib/jquery.js

**Comment by mdwhatcott** [comment]
Thanks for taking the time to report the issue. Can you be more specific? What problem are you encountering? What are the steps to reproduce the issue?

**Comment by devinceble** [comment]
file jquery.js only contains jquery-2.1.0.js text while running goconvey it will not start web ui.

**Comment by devinceble** [comment]
Using Windows 10 + cmder
![goconvey](https://cloud.githubusercontent.com/assets/4859257/13517159/d2aaf2b6-e1fb-11e5-9488-85a93a3713b5.png)

**Comment by devinceble** [comment]
I've temporarily fix buy replacing jquery.js with jquery-2.1.0.js but some goconvey web ui buttons won't function. Maybe its windows 10 and cmder problem.

**Comment by onlyjob** [comment]
> file jquery.js only contains jquery-2.1.0.js

What do you mean?? jquery.js contains jQuery -- isn't that what one would expect??
`jquery.js` is actually a symlink to `jquery-2.1.0.js`...

> I've temporarily fix buy replacing jquery.js with jquery-2.1.0.js

Is your issue fixed when you delete symlink and rename `jquery-2.1.0.js` to `jquery.js`?
Can you confirm that symlink is actually a problem? 

Also maybe you could try with newer https://code.jquery.com/jquery-2.2.1.js?
Thanks.

**Comment by riannucci** [comment]
Is it possible that the symlink is not working on your windows version of git?

**Comment by devinceble** [comment]
Yep symlink is the problem for windows. I tried goconvey back at home using arch works fine. Thanks
