### ISSUE TITLE
jquery does not work on Windows

### ISSUE THREAD

**Issue by mbp** [smartystreets/goconvey#405]
This is a continuation of #399

Goconvey web interface does not work on latest master when using Windows, because jquery was not defined. 

The file `web\client\resources\js\lib.jquery.js` contains the string `jquery-2.1.0.js`, instead of a symlink to the file. I am using Git 2.7.2.

If I checkout commit bf58a9a1291224109919756b4dcc469c670cc7e4 then everything works as expected on Windows.

**Comment by cristian-sima** [comment]
+1

**Comment by cristian-sima** [comment]
> If I checkout commit `bf58a9a` then everything works as expected on Windows.

How do you do this?

**Comment by mbp** [comment]
`cd $GOPATH/src/github.com/smartystreets/goconvey && git checkout bf58a9a`

**Comment by cristian-sima** [comment]
Tx mate. It works. 

Guys you should fix it on main branch

**Comment by mdwhatcott** [comment]
@cristian-sima - I'm sorry to hear that a recent update has broken the GUI on windows. This is an open source project so you are welcome to submit a fix for this issue if you'd like. We don't develop go code on Windows at smartystreets so it's not a situation we encounter or even have much motivation to support.

@onlyjob - can you help with this issue? I could be wrong but it seems to be a direct result of your un-minification updates.

**Comment by onlyjob** [comment]
> can you help with this issue? I could be wrong but it seems to be a direct result of your un-minification updates.

@mdwhatcott, #407 should fix it.

**Comment by VorT3x** [comment]
@onlyjob have you checked it on Windows?

**Comment by mdwhatcott** [comment]
Thanks!

**Comment by onlyjob** [comment]
> @onlyjob have you checked it on Windows?

Of course not! I don't have windows.
This change is so simple, safe and straightforward that it needs no checking.
I merely removed symlink (introduced earlier) and replaced it with file as it used to be.

**Comment by mdwhatcott** [comment]
> This change is so simple, safe and straightforward that it needs no checking.

I've heard that before... :)

**Comment by VorT3x** [comment]
No worries, had to run my Windows 10 virtual machine & setup GO there to check it ;)

**Comment by onlyjob** [comment]
> I've heard that before... :)

:-) :-)
