### ISSUE TITLE
Option to only show notifications on test failures (successful runs silent)

### ISSUE THREAD

**Issue by toftware** [smartystreets/goconvey#406]
I think it would be great to be able to disable the notifications when the tests succeeds.

**Comment by riannucci** [comment]
To clarify: you'd only want to see notifications when the tests fail?

Two thoughts spring to mind:
  * Have the bell be a dropdown with {Off, Failures, Always} options
  * Have the bell icon cycle to a third state (maybe a Bell-with-an-exclaimation mark)?

**Comment by toftware** [comment]
Yes exactly, since i feel getting a toast notification with "Everything is working as expected" can be a bit disruptive.

Some kind of indicator like an exclamation mark or a star would be a good idea go give visual feedback.
