### ISSUE TITLE
Do not open a new tab when starting goconvey again

### ISSUE THREAD

**Issue by magicalbanana** [smartystreets/goconvey#411]
So is it possible right now? When I stop goconvey, and start it again it opens a new tab while an existing tab to the server already exists. Because the problem is, when I start goconvey the existing tab reattempts the connection and starts it all over again.

**Comment by jlovison** [comment]
Yeah, this was a shock after upgrading. The behavior to open a new tab should at least be able to be controlled via a command line flag.

**Comment by ruzz311** [comment]
Pull #420 addresses this.  You can start goconvey with the option ```goconvey -launchBrowser=false``` to avoid the default behavior.
