### ISSUE TITLE
Can not open the stories

### ISSUE THREAD

**Issue by cristian-sima** [smartystreets/goconvey#413]
Hi.

I have a issues and I can not open the stories.

When I press on the plus button, nothing happens

![image](https://cloud.githubusercontent.com/assets/12199042/14060331/e9387038-f369-11e5-8834-84820c473fa9.png)

I can see in the JavaScript console that there is a problem somewhere

![image](https://cloud.githubusercontent.com/assets/12199042/14060335/0759b8e2-f36a-11e5-9d96-a455cfaa0e5a.png)

Thanks

**Comment by ruzz311** [comment]
I saw this recently too - looks like it happened when there was an update to jquery.  The live option on jquery.tipsy no longer works.  I've got a PR coming that should fix this.

**Comment by MaikuMori** [comment]
Would be nice to get this merged into master.
