### ISSUE TITLE
Empty testify suite fails with ???

### ISSUE THREAD

**Issue by petomalina** [smartystreets/goconvey#432]
This code fails with the convey FAIL and output`???`. The output of the console from the `go test` is ok and also tells that there are no tests to run somewhere. 

```
testing: warning: no tests to run
PASS
ok      github.com/flowup/gogen 0.007s
```

``` go
import (
  "github.com/stretchr/testify/suite"
  "testing"
)

type ParseFunctionSuite struct {
    suite.Suite
}

func TestParseFunctionSuite(t *testing.T) {
    suite.Run(t, &ParseFunctionSuite{})
}
```

Is there any possibility to catch this situation? The FAIL ??? does not really tell anything and may lead to wrong debugging.

**Comment by ruzz311** [comment]
With testify there's nothing being asserted in the "run" function.  You'll need to add a method receiver to the ParseFunctionSuite with some asserts.

**Comment by gelidus** [comment]
Well yeah, but the suite should fail with that error, instead of full set. Goconvey should recover from this and tell that there are no tests in the suite (if this can be done).

**Comment by petomalina** [comment]
Closing this as it looks like the issue is dead
