### ISSUE TITLE
gconvey in docker?

### ISSUE THREAD

**Issue by jimmiebtlr** [smartystreets/goconvey#449]
# Expected Behavior

Running inside a docker container and exposing port 8080 should allow me to connect to the tests.  The sample test runs outside docker, as does goconvey.
# Actual behavior

I'm not able to connect on port 8080, and the build is listed as failed.
# Details

```
FROM golang:1.7

EXPOSE 8080

RUN go get github.com/smartystreets/goconvey

COPY . /go/src/github.com/org/repo
WORKDIR /go/src/github.com/org/repo

CMD goconvey
```

```
2016/10/06 04:01:10 goconvey.go:61: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2016/10/06 04:01:10 tester.go:19: Now configured to test 10 packages concurrently.
2016/10/06 04:01:10 goconvey.go:192: Serving HTTP at: http://127.0.0.1:8080
2016/10/06 04:01:10 goconvey.go:105: Launching browser on 127.0.0.1:8080
2016/10/06 04:01:10 goconvey.go:111: exec: "xdg-open": executable file not found in $PATH
2016/10/06 04:01:10 goconvey.go:113: 
2016/10/06 04:01:10 integration.go:122: File system state modified, publishing current folders... 0 2951418315
2016/10/06 04:01:10 goconvey.go:118: Received request from watcher to execute tests...
2016/10/06 04:01:10 executor.go:69: Executor status: 'executing'
2016/10/06 04:01:10 coordinator.go:46: Executing concurrent tests: github.com/org/repo
2016/10/06 04:01:10 parser.go:24: [build failure]: github.com/org/repo
2016/10/06 04:01:10 executor.go:69: Executor status: 'idle'
```

`docker build --no-cache -t "ssp" .; docker run -p "8080:8080" "ssp"`

**Comment by tikiatua** [comment]
Hi there,

docker does only allow port forwarding from host 0.0.0.0. Goconvey is started on host 127.0.0.1 per default. You need to set the host to 0.0.0.0 per command line flag and everything should work as expected.

`CMD goconvey -host 0.0.0.0`

We developed a small container that supports goconvey, automatic building and automatic run of `go test` for anyone interested https://github.com/dkfbasel/hot-reload. The respective docker image is `dkfbasel/hot-reload-go:1.8.1`.

**Comment by jimmiebtlr** [comment]
0.0.0.0 was key, thanks
