### ISSUE TITLE
If goconvey runs 2 days after in VirtualBox, it will consume all memory and can not stop.

### ISSUE THREAD

**Issue by penhauer-xiao** [smartystreets/goconvey#461]
As title

**Comment by teubanks** [comment]
Seeing this on a mac as well.
Current version is `3bd662eac601ad6436e64776af2e112069eb2edc` (I guess there's no `--version` option?)

![screen shot 2017-06-21 at 10 25 58 am](https://user-images.githubusercontent.com/82216/27392419-423da0b6-566c-11e7-9293-fe12a5a11c77.png)

**Comment by ghostsquad** [comment]
What does this even mean? Can you provide repro steps? Screenshots? Literally any additional information would be great.
