### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by AlekSi** [smartystreets/goconvey#485]
There are some fixes which are not released yet. For example, 1.6.2 doesn't work with tip version of Go.

**Comment by nkovacs** [comment]
And https://github.com/smartystreets/assertions too, please.

**Comment by AlekSi** [comment]
Bump. Go 1.9 is going to be released in a few days.

**Comment by vort3x** [comment]
https://github.com/smartystreets/goconvey/releases/tag/1.6.3
