### ISSUE TITLE
comparisons to nil don't work as expected for error values

### ISSUE THREAD

**Issue by GrandOpener** [smartystreets/goconvey#492]
I think this broke recently because I only started getting failures after a recent `go get -u`, but comparisons to nil are unexpectedly failing now.

```
// main.go
package main

func main() {

}

func returnNil() error {
	return nil
}
```
```
// maintest.go
package main

import (
	"testing"

	. "github.com/smartystreets/goconvey/convey"
)

func TestEqualNil(t *testing.T) {
	Convey("Given a nil error", t, func() {
		err := returnNil()
		Convey("it should be equal to nil", func() {
			So(err, ShouldEqual, nil)
			So(err, ShouldBeNil)
		})
	})
}
```

Do I need to use ShouldResemble since error is an interface?  Maybe I'm hallucinating, but I'm 100% sure the equal tests used to work...

**Comment by pschuegr** [comment]
@GrandOpener I see there is an assertion on the wiki "ShouldBeNil".  Not sure how old that is.

**Comment by dsmontoya** [comment]
They used to work. Now, even the following assertion fails:
```go
So(nil, ShouldEqual, nil)
```

I'm not familiar with the source code, but could be related to https://github.com/smartystreets/assertions/commit/f5a4bca0a2a67558e95ed599ab02f31094e9603e

**Comment by mdwhatcott** [comment]
Sorry everyone! Looks like I forgot a test case. Should be fixed now.
