### ISSUE TITLE
Exclusive Convey

### ISSUE THREAD

**Issue by joliver** [smartystreets/goconvey#52]
Could you please add the ability the run only a specific convey? This would eliminate the need to use SkipConvey on other sections.  Perhaps it could be called OnlyConvey or something similar.

**Comment by danielalves** [comment]
Hey, this (quite old) feature is what I was looking for! It would be great if it was documented in the Wiki so other people can find it faster :smile:

**Comment by mdwhatcott** [comment]
The wiki is open for editing--feel free to create a page if you'd like. @danielalves

**Comment by danielalves** [comment]
:+1:

**Comment by edbedbe** [comment]
Added a basic summary and usage example to the wiki: https://github.com/smartystreets/goconvey/wiki/Skip#running-only-certain-convey-registrations

**Comment by ezk84** [comment]
Is it not possible to have just a single deep FocusConvey, similar to the way jasmine allows a `fit` to just run a single test case without having to change the `describe` to `fdescribe`?

Having to change all conveys up the tree doesn't really allow to quickly run a single problematic test case.
