### ISSUE TITLE
CSS .depth-# 8 level and above do not exist

### ISSUE THREAD

**Issue by Megalepozy** [smartystreets/goconvey#536]
Hey oh,

So if I got a pretty hefty (yeah I know..) tree of Convey() which is more then 7 levels, the levels which are higher then 7 start at the start (left) of their line and not in a position which is relative to their parent and a little to the right.

Basically the code miss some few CSS classes definitions, though I guess that it can be done to be dynamically (not sure, don't really know CSS).

Thanks for this amazing project! :)

**Comment by Megalepozy** [comment]
btw I can make a pull request with some extra css definitions if its helpful (its at common.css)

**Comment by MattLish** [comment]
@Megalepozy Did you ever do this?

**Comment by Megalepozy** [comment]
@markbates Yeah I did it locally but then decided that my testing code is wrong if I need so many levels so I refactored everything and forgot about this issue, honestly I should have closed it... will do it now

**Comment by MattLish** [comment]
I can still see a case where it might be useful.

I use BDD and sometimes I have an AND or 2.

It could look like this

>Feature: User trades stocks
>      Scenario: User requests a sell before close of trading
>          Given I have 100 shares of MSFT stock
>             And I have 150 shares of APPL stock
>                  And the time is before close of trading
>                       When I ask to sell 20 shares of MSFT stock
>                            AND something else
>                                 Then I should have 80 shares of MSFT stock

In goconvey I can't see a way to make the WHEN and AND live next to each other so they must be nested.

I might make a PR for this.
