### ISSUE TITLE
If func So 's first argument is void interface, how to make So work?

### ISSUE THREAD

**Issue by KielChan** [smartystreets/goconvey#546]
if i have function like this:
```golang
func DemoVoidReturn(){
    fmt.Println("test empty return")

    if err := doSomething(); err != nil{
        panic("do something failed")
    }
}
```

and i want to test this panic.

how to use `So` to test it?

**Comment by mdwhatcott** [comment]
Your function in a void (no return values), niladic (no input parameters) function and the perform the assertion.

`So(wrapperFunction, should.Panic)`
