### ISSUE TITLE
question: goconvey input format

### ISSUE THREAD

**Issue by brizjin** [smartystreets/goconvey#550]
Is there any documentation, how is goconvey read its input? I working on python testing I have option to visualize results of tests in bdd style with yandex.allure. But it is has not have this amazing online reloading feature as goconvey has. For examle allure eats folder with json files and make visualization from it. Is there any way make such online test results visualization by goconvey from other languages, python in my case, what is format input data shuold I prepare for them? Thank you!

**Comment by mdwhatcott** [comment]
The goconvey server executes test and converts the output into JSON which is sent back to the client/browser. The javascript on the html page takes care of rendering the JSON. Have a look in the "network" tab of your browser's developer tools to inspect the actual JSON data being processed by the browser. That will hopefully give you an idea of how to build your own in-browser test runner.
