### ISSUE TITLE
Build issues with Go 1.11.5

### ISSUE THREAD

**Issue by 0nedark** [smartystreets/goconvey#556]
I've been trying to setup goconvey as my testing framework and I seem to have encountered a problem with the latest go version, tests seem to pass but the build fails with the following error.

> can't load package: package github.com/0nedark/serv/src: unknown import path "github.com/0nedark/serv/src": cannot find module providing package github.com/0nedark/serv/src

You can replicate this with (I assume you have `docker`, `docker-compose` and `make` installed)

1. `git clone https://github.com/0nedark/serv.git && cd serv && make`
2. Open `localhost:8080` in your browser

**Comment by peterrosell** [comment]
I have got the same problem. It seem like go 1.11 gives another error message when goconvey try to run a build command in a directory without go files.

**Comment by peterrosell** [comment]
Created a PR #558

**Comment by riannucci** [comment]
(this was fixed)
