### ISSUE TITLE
Top-level calls to Convey for Go1.12

### ISSUE THREAD

**Issue by tietang** [smartystreets/goconvey#559]
--- FAIL: TestGetAccount (0.00s)
panic: Top-level calls to Convey(...) need a reference to the *testing.T.
		Hint: Convey("description here", t, func() { /* notice that the second argument was the *testing.T (t)! */ })  [recovered]
	panic: Top-level calls to Convey(...) need a reference to the *testing.T.
		Hint: Convey("description here", t, func() { /* notice that the second argument was the *testing.T (t)! */ })  [recovered]
	panic: Top-level calls to Convey(...) need a reference to the *testing.T.
		Hint: Convey("description here", t, func() { /* notice that the second argument was the *testing.T (t)! */ }) 

`
func TestGetAccount(t *testing.T) {

	Convey("test1", t, func() {
		Convey("test1-1", func() {
			 //...
		})
	})
}`

**Comment by tietang** [comment]
`Convey(message, t, func() {
		 
		So(sum, ShouldEqual, amount)
	 
	})`
--- FAIL: TestSimpleRand (0.00s)
panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ? [recovered]
	panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ? [recovered]
	panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ?

goroutine 18 [running]:
testing.tRunner.func1(0xc0000ec100)
	/Users/tietang/java/go/src/testing/testing.go:830 +0x388
panic(0x1176020, 0xc0000904b0)
	/Users/tietang/java/go/src/runtime/panic.go:522 +0x1b5
github.com/smartystreets/goconvey/convey.(*context).conveyInner.func2(0xc000088240)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:232 +0x1c6
panic(0x1176020, 0xc0000904b0)
	/Users/tietang/java/go/src/runtime/panic.go:522 +0x1b5
github.com/smartystreets/goconvey/convey.conveyPanic(...)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:20
github.com/smartystreets/goconvey/convey.mustGetCurrentContext(0x21)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:52 +0x111
github.com/smartystreets/goconvey/convey.So(0x11672e0, 0xc00009c1c0, 0x11b16d0, 0xc00008e3b0, 0x1, 0x1)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/doc.go:125 +0x22
imooc.com/resk/infra/algo.ForTest.func1()
	/Users/tietang/my/gitcode/resk-projects/src/imooc.com/resk/infra/algo/algo_test.go:32 +0xc0
github.com/smartystreets/goconvey/convey.parseAction.func1(0x11dda00, 0xc000088240)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x24
github.com/smartystreets/goconvey/convey.(*context).conveyInner(0xc000088240, 0x11a954e, 0x12, 0xc00008e390)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x154
github.com/smartystreets/goconvey/convey.rootConvey.func1()
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:110 +0xf1
github.com/jtolds/gls._m(0x0, 0xc000098180)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/stack_tags.go:70 +0x31
github.com/jtolds/gls.markS(...)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/stack_tags.go:21
github.com/jtolds/gls.addStackTag(...)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/stack_tags.go:18
github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000980a0, 0xc000090420, 0xc000098180)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/context.go:98 +0x4a8
github.com/smartystreets/goconvey/convey.rootConvey(0xc000074f38, 0x3, 0x3)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:105 +0x22b
github.com/smartystreets/goconvey/convey.Convey(0xc000074f38, 0x3, 0x3)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0xbf
imooc.com/resk/infra/algo.ForTest(0x11a954e, 0x12, 0xc0000ec100, 0x11b1790)
	/Users/tietang/my/gitcode/resk-projects/src/imooc.com/resk/infra/algo/algo_test.go:30 +0x146
imooc.com/resk/infra/algo.TestSimpleRand(0xc0000ec100)
	/Users/tietang/my/gitcode/resk-projects/src/imooc.com/resk/infra/algo/algo_test.go:10 +0x4c
testing.tRunner(0xc0000ec100, 0x11b17b0)
	/Users/tietang/java/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/Users/tietang/java/go/src/testing/testing.go:916 +0x357

**Comment by tietang** [comment]
`Convey(message, t, func() {
		Convey(message, func() {
			So(sum, ShouldEqual, amount)
		})
	})`


--- FAIL: TestSimpleRand (0.00s)
panic: Top-level calls to Convey(...) need a reference to the *testing.T.
		Hint: Convey("description here", t, func() { /* notice that the second argument was the *testing.T (t)! */ })  [recovered]
	panic: Top-level calls to Convey(...) need a reference to the *testing.T.
		Hint: Convey("description here", t, func() { /* notice that the second argument was the *testing.T (t)! */ })  [recovered]
	panic: Top-level calls to Convey(...) need a reference to the *testing.T.
		Hint: Convey("description here", t, func() { /* notice that the second argument was the *testing.T (t)! */ }) 

goroutine 4 [running]:
testing.tRunner.func1(0xc0000c4100)
	/Users/tietang/java/go/src/testing/testing.go:830 +0x388
panic(0x1176200, 0xc000064570)
	/Users/tietang/java/go/src/runtime/panic.go:522 +0x1b5
github.com/smartystreets/goconvey/convey.(*context).conveyInner.func2(0xc00004e1e0)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:232 +0x1c6
panic(0x1176200, 0xc000064570)
	/Users/tietang/java/go/src/runtime/panic.go:522 +0x1b5
github.com/smartystreets/goconvey/convey.conveyPanic(...)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:20
github.com/smartystreets/goconvey/convey.rootConvey(0xc00006ca60, 0x2, 0x2)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:91 +0x35c
github.com/smartystreets/goconvey/convey.Convey(0xc00006ca60, 0x2, 0x2)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0xbf
imooc.com/resk/infra/algo.ForTest.func1()
	/Users/tietang/my/gitcode/resk-projects/src/imooc.com/resk/infra/algo/algo_test.go:31 +0xec
github.com/smartystreets/goconvey/convey.parseAction.func1(0x11ddd00, 0xc00004e1e0)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x24
github.com/smartystreets/goconvey/convey.(*context).conveyInner(0xc00004e1e0, 0x11a97ee, 0x12, 0xc000042510)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x154
github.com/smartystreets/goconvey/convey.rootConvey.func1()
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:110 +0xf1
github.com/jtolds/gls._m(0x0, 0xc00000c1e0)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/stack_tags.go:70 +0x31
github.com/jtolds/gls.markS(...)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/stack_tags.go:21
github.com/jtolds/gls.addStackTag(...)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/stack_tags.go:18
github.com/jtolds/gls.(*ContextManager).SetValues(0xc00000c100, 0xc0000644e0, 0xc00000c1e0)
	/Users/tietang/java/go_third/src/github.com/jtolds/gls/context.go:98 +0x4a8
github.com/smartystreets/goconvey/convey.rootConvey(0xc00006cf38, 0x3, 0x3)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/context.go:105 +0x22b
github.com/smartystreets/goconvey/convey.Convey(0xc00006cf38, 0x3, 0x3)
	/Users/tietang/java/go_third/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0xbf
imooc.com/resk/infra/algo.ForTest(0x11a97ee, 0x12, 0xc0000c4100, 0x11b1a30)
	/Users/tietang/my/gitcode/resk-projects/src/imooc.com/resk/infra/algo/algo_test.go:30 +0x15b
imooc.com/resk/infra/algo.TestSimpleRand(0xc0000c4100)
	/Users/tietang/my/gitcode/resk-projects/src/imooc.com/resk/infra/algo/algo_test.go:10 +0x4c
testing.tRunner(0xc0000c4100, 0x11b1a50)
	/Users/tietang/java/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/Users/tietang/java/go/src/testing/testing.go:916 +0x357

**Comment by mjl-** [comment]
i ran into this yesterday with a codebase that uses goconvey.

the problem seems to be that https://github.com/jtolds/gls (read the page...) doesn't work anymore. i think this can be solved by adding a parameter to the (last) function parameter to all the Convey() calls: a "c C", and change your So() calls to c.So() and the nested Convey() calls to c.Convey().  i think that prevents use/dependency on the gls library.

see https://github.com/smartystreets/goconvey/blob/master/convey/context.go#L59

i'm trying these changes on the codebase i'm working on today, hope it works out. if there are better solutions, i'm interested in hearing about it...

**Comment by tietang** [comment]
I delete pkg/../*.a file and delete `goconvey` and `gls` code .
And reinstalled `goconvey` and `gls` , so the problem was solved and  fixed it.

**Comment by un000** [comment]
Have the same issue, but using vendor

**Comment by tietang** [comment]
@un000 u can delete `goconvey` and `gls` lib from vendor，and delete from pkg in projects 。reinstalled and try？

**Comment by wwwjfy** [comment]
@tietang can we keep the issue open unless someone finds out the root cause?

**Comment by tietang** [comment]
@wwwjfy I guess is that `.a` format is incompatible.  
so you can reinstalled and try, if there is still the problem，and I will reopen the issue. How's that？

**Comment by wwwjfy** [comment]
Tried, still get the errors
I deleted the whole vendor folder in my project; deleted $GOPATH/pkg; ran `go mod vendor`

**Comment by un000** [comment]
deleting go/mod cache & vendor + go mod vendor didn't work

**Comment by wwwjfy** [comment]
we can move the discussion to #561

**Comment by tietang** [comment]
@wwwjfy  @un000  👌

**Comment by tietang** [comment]
@un000 @wwwjfy  I've tried `go dep` and `go get`, it works.

**Comment by wwwjfy** [comment]
I think it's related to how `gls` works, not about dependency managers. have raised issue with code to reproduce it. https://github.com/jtolds/gls/issues/14

**Comment by tietang** [comment]
@un000 @wwwjfy   You can delete project `pkg` and  GOPATH `pkg` ... all ` [jtolds/gls]`,and  try it?

**Comment by wwwjfy** [comment]
There is no _project_ `pkg` and I've deleted the GOPATH `pkg` and `src`. BTW there is no compiled binary for goconvey and gls there.

**Comment by tietang** [comment]
> I think it's related to how `gls` works, not about dependency managers. have raised issue with code to reproduce it. [jtolds/gls#14](https://github.com/jtolds/gls/issues/14)

I'v debug gls, The call sequence is different  between go1.11.5 and go1.12.
 In go1.12,The call sequence is incredible !!!

For go1.11.5:

```
 github.com/smartystreets/goconvey/convey.(*context).conveyInner |  1
 github.com/smartystreets/goconvey/convey.rootConvey.func1 |  1
 **github.com/jtolds/gls._m |  1**
 **github.com/jtolds/gls.markS | 2**
 **github.com/jtolds/gls.addStackTag |  1**
 **github.com/jtolds/gls.(*ContextManager).SetValues |  1**
 github.com/smartystreets/goconvey/convey.rootConvey |  1
 github.com/smartystreets/goconvey/convey.Convey |  1
```

for go1.12:

```
 github.com/smartystreets/goconvey/convey.(*context).conveyInner |  1
 github.com/smartystreets/goconvey/convey.rootConvey.func1 |  1
 **github.com/jtolds/gls._m |  1**
 **github.com/jtolds/gls.(*ContextManager).SetValues |  1**
 **github.com/jtolds/gls.markS | 2**
 **github.com/jtolds/gls.addStackTag |  1**
 github.com/smartystreets/goconvey/convey.rootConvey |  1
 github.com/smartystreets/goconvey/convey.Convey |  1
```

**Comment by tietang** [comment]
I found, after I'v updated 'gls', 

you can check code: `github.com/jtolds/gls/stack_tags.go:114`, the  function `readStackTag` is the same  as the following:

```
func readStackTag() (tag uint, ok bool) {
	var current_tag uint
	offset := 0
	for {
		batch, next_offset := getStack(offset, stackBatchSize)
		for _, pc := range batch {
			val, ok := pc_lookup[pc]
			if !ok {
				continue
			}
			if val < 0 {
				return current_tag, true
			}
			current_tag <<= bitWidth
			current_tag += uint(val)
		}
		if next_offset == 0 {
			break
		}
		offset = next_offset
	}
	return 0, false
}

```

if not, you can update lib 'gls', may delete it and update it again.

**Comment by wwwjfy** [comment]
I don't see any reasoning behind this as I've deleted the pkg multiple times.
To be safe, I tried in clean Docker containers, and got the same errors.

**Comment by wwwjfy** [comment]
I think the last commit of `gls` fixed the issue, but it's tagged as 4.20 which is not a valid go version.
Not sure if @tietang succeeded because of this, maybe he cloned the gls repo instead of using `go get`.
I tried to manually apply last commit to `gls` 4.2.1 and the errors no longer appeared.

**Comment by tietang** [comment]
@wwwjfy it should be the reason, before the method `readStackTag` is implemented differently, that I debug the version.

**Comment by wwwjfy** [comment]
> @wwwjfy it should be the reason, before the method `readStackTag` is implemented differently, that I debug the version.

Sorry, but no. The last commit of `gls` is to prevent compiler to optimize code to inline functions. https://github.com/jtolds/gls/commit/b4936e06046bbecbb94cae9c18127ebe510a2cb9

I guess you were using an older than 4.2.1 version which had a different `readStackTag` implementation, but I don't think it's related. The only patch I applied and worked is the `go:noinline` one

**Comment by songtianyi** [comment]
what's the solution?

**Comment by NaLLiFFuNT** [comment]
I had the same problem while trying to upgrade from go1.11.12. I've found out that [someone has successfully uses goconvey with latest go1.13.3](https://github.com/scionproto/scion/issues/3009#issuecomment-548728993) version.
Here what has helped me:
1) Remove all mentions of `goconvey` from your `go.sum` & `go.mod` file
2) Upgrade go version
3) Run `go mod tidy`
4) Run tests to check wheather it's working

I've ended up with go version `1.13.5` and goconvey version `v1.6.4`
