### ISSUE TITLE
gcflags 

### ISSUE THREAD

**Issue by max-min** [smartystreets/goconvey#572]
[Monkey](https://github.com/bouk/monkey) sometimes fails to patch a function if inlining is enabled. Try running your tests with inlining disabled, for example: `go test -gcflags=-l`

but when i use this package web sevice。 how to  add `-gcflags=-1` parameter?

**Comment by CarlBye** [comment]
It seems that convey doesn't support to add argument when execute `go test`. So u may need to patch functions that inline function calls instead.

**Comment by max-min** [comment]
> It seems that convey doesn't support to add argument when execute `go test`. So u may need to patch functions that inline function calls instead.

tks。

**Comment by CarlBye** [comment]
Actually, I give u a wrong answer. When I add the args directly, no problems occurs. Can u describe more details.
