### ISSUE TITLE
Cannot find goconvey in $GOPATH/bin/

### ISSUE THREAD

**Issue by FosuLiang** [smartystreets/goconvey#670]
Why I can not find goconvey  in $GOPATH/bin/? I do really download gonconvey by command:
`go get github.com/smartystreets/goconvey`
package is download successfully but without goconvey in $GOPATH/bin/

**Comment by grafov** [comment]
The `go get` behaviour was changed in the latest Go versions. Try this:
```
go install github.com/smartystreets/goconvey@latest
```

**Comment by FosuLiang** [comment]
Thx a lot! It's solved.
