### ISSUE TITLE
Coverage reports fail w/ go1.20

### ISSUE THREAD

**Issue by cognusion** [smartystreets/goconvey#672]
I haven't dug into this, yet, but the coverage reports are no longer rendering. The only output of note from `goconvey` itself is:

`2023/02/03 15:31:56 shell.go:91: Run without coverage`

I manually ran with `-cover=true` but the result was the same. Again, I expect a problem parsing the new format. I'll update after I've dug in a bit.

**Comment by NajeebTyson** [comment]
I also ran into the same problem with go1.20, when I downgraded the version to go19.9 it worked.

**Comment by flier** [comment]
It looks like the test output format has changed from go 1.20

```
PASS
	github.com/flier/gohs/hyperscan	coverage: 74.2% of statements
ok  	github.com/flier/gohs/hyperscan	0.939s	coverage: 74.2% of statements
```

The current `goconvey` assume the `coverage: ` at the beginning of line.

```go
var coverageStatementRE = regexp.MustCompile(`(?m)^coverage: \d+\.\d% of statements(.*)$|^panic: test timed out after `)
```

**Comment by cognusion** [comment]
Looks like this was fixed either here or in a recent go version. Thank you (or not)!
