### ISSUE TITLE
Benchmark integration

### ISSUE THREAD

**Issue by aaasen** [smartystreets/goconvey#97]
Go's testing package also supports [benchmarks](http://golang.org/pkg/testing/). However, benchmarks are somewhat difficult to run, and I usually forget to run mine regularly. It would be awesome if GoConvey could run them automatically and detect changes over time.

This would be a sizable addition, so I wanted to make sure that it aligned with the goals of the project before beginning work.

**Comment by P-VINODKRISHNA** [comment]
how benchmarking can be done using goconvey
