### ISSUE TITLE
Code that calls panic is NOT reported as such

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/goconvey#98]
@swaits submitted an example that called `panic` yet GoConvey calmly reported no errors. As expected, execution stopped after the `panic` because none of the assertions that followed the panic were executed or reported. Very strange.

**Comment by mdwhatcott** [comment]
https://github.com/golang/go/issues/25448

**Comment by mdwhatcott** [comment]
Well, 10 years later with the release of Go 1.21, we finally have closure!

> Go 1.21 now defines that if a goroutine is panicking and recover was called directly by a deferred function, the return value of recover is guaranteed not to be nil. To ensure this, calling panic with a nil interface value (or an untyped nil) causes a run-time panic of type [*runtime.PanicNilError](https://go.dev/pkg/runtime/#PanicNilError).

https://go.dev/doc/go1.21

**Comment by swaits** [comment]
Wow, nice @mdwhatcott!
